// CHECKSTYLE:FileLength:off (reason:generated)
// CHECKSTYLE:LineLength:off (reason:generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESATObject;


/**
 * Generated interface definition for application table AS_IM_OilFillingResult.
 * Application table description: null
 * @ftps.exclude 
 */
public interface IMESGeneratedASIMOilFillingResult extends IMESATObject {

    /** Generated attribute definition */
    public static final String ATDEFINITION_NAME = "AS_IM_OilFillingResult";


    /** Generated property name */
    public static final String PROP_NAME_CYCLEFAULT = "cyclefault";

    /** Generated column name */
    public static final String SQL_COL_NAME_CYCLEFAULT = "cycle_fault_S";
    

    /** Generated property name */
    public static final String PROP_NAME_CYCLENO = "cycleno";

    /** Generated column name */
    public static final String SQL_COL_NAME_CYCLENO = "cycle_no_S";
    

    /** Generated property name */
    public static final String PROP_NAME_CYCLERESULT = "cycleresult";

    /** Generated column name */
    public static final String SQL_COL_NAME_CYCLERESULT = "cycle_result_S";
    

    /** Generated property name */
    public static final String PROP_NAME_CYCLETIMES = "cycletimes";

    /** Generated column name */
    public static final String SQL_COL_NAME_CYCLETIMES = "cycle_time_s_S";
    

    /** Generated property name */
    public static final String PROP_NAME_DATETIME = "datetime";

    /** Generated column name */
    public static final String SQL_COL_NAME_DATETIME = "date_time_S";
    

    /** Generated property name */
    public static final String PROP_NAME_DELTADIFFERPRESSUREB = "deltadifferpressureb";

    /** Generated column name */
    public static final String SQL_COL_NAME_DELTADIFFERPRESSUREB = "delta_differ_pressure_b_S";
    

    /** Generated property name */
    public static final String PROP_NAME_DELTAPRESSURECHECKB = "deltapressurecheckb";

    /** Generated column name */
    public static final String SQL_COL_NAME_DELTAPRESSURECHECKB = "delta_pressure_check_b_S";
    

    /** Generated property name */
    public static final String PROP_NAME_EXPANSIONTANKVOLUMEI = "expansiontankvolumei";

    /** Generated column name */
    public static final String SQL_COL_NAME_EXPANSIONTANKVOLUMEI = "expansion_tank_volume_i_S";
    

    /** Generated property name */
    public static final String PROP_NAME_FILLINGPRESSUREVALUEB = "fillingpressurevalueb";

    /** Generated column name */
    public static final String SQL_COL_NAME_FILLINGPRESSUREVALUEB = "filling_pressure_value_b_S";
    

    /** Generated property name */
    public static final String PROP_NAME_LOCATION = "location";

    /** Generated column name */
    public static final String SQL_COL_NAME_LOCATION = "location_S";
    

    /** Generated property name */
    public static final String PROP_NAME_MOBILEUNITNO = "mobileunitno";

    /** Generated column name */
    public static final String SQL_COL_NAME_MOBILEUNITNO = "mobile_unit_no_S";
    

    /** Generated property name */
    public static final String PROP_NAME_MULTIMIXINGVOLUMEI = "multimixingvolumei";

    /** Generated column name */
    public static final String SQL_COL_NAME_MULTIMIXINGVOLUMEI = "multi_mixing_volume_i_S";
    

    /** Generated property name */
    public static final String PROP_NAME_PAGOILVOLUMEML = "pagoilvolumeml";

    /** Generated column name */
    public static final String SQL_COL_NAME_PAGOILVOLUMEML = "pag_oil_volume_ml_S";
    

    /** Generated property name */
    public static final String PROP_NAME_PROCESSTYPE = "processtype";

    /** Generated column name */
    public static final String SQL_COL_NAME_PROCESSTYPE = "process_type_S";
    

    /** Generated property name */
    public static final String PROP_NAME_RES1 = "res1";

    /** Generated column name */
    public static final String SQL_COL_NAME_RES1 = "res1_S";
    

    /** Generated property name */
    public static final String PROP_NAME_RES2 = "res2";

    /** Generated column name */
    public static final String SQL_COL_NAME_RES2 = "res2_S";
    

    /** Generated property name */
    public static final String PROP_NAME_RES3 = "res3";

    /** Generated column name */
    public static final String SQL_COL_NAME_RES3 = "res3_S";
    

    /** Generated property name */
    public static final String PROP_NAME_RES4 = "res4";

    /** Generated column name */
    public static final String SQL_COL_NAME_RES4 = "res4_S";
    

    /** Generated property name */
    public static final String PROP_NAME_SERIALNUMBER = "serialnumber";

    /** Generated column name */
    public static final String SQL_COL_NAME_SERIALNUMBER = "serial_number_S";
    

    /** Generated property name */
    public static final String PROP_NAME_TEMPERATUREVALUEOC = "temperaturevalueoc";

    /** Generated column name */
    public static final String SQL_COL_NAME_TEMPERATUREVALUEOC = "temperature_value_oc_S";
    

    /** Generated property name */
    public static final String PROP_NAME_TESTAIRRESIDUALCL = "testairresidualcl";

    /** Generated column name */
    public static final String SQL_COL_NAME_TESTAIRRESIDUALCL = "test_air_residual_cl_S";
    

    /** Generated property name */
    public static final String PROP_NAME_UNITY = "unity";

    /** Generated column name */
    public static final String SQL_COL_NAME_UNITY = "unity_S";
    

    /** Generated property name */
    public static final String PROP_NAME_VACUUM1VALUEMB = "vacuum1valuemb";

    /** Generated column name */
    public static final String SQL_COL_NAME_VACUUM1VALUEMB = "vacuum_1_value_mb_S";
    

    /** Generated property name */
    public static final String PROP_NAME_VACUUMCHECKVALUEMB = "vacuumcheckvaluemb";

    /** Generated column name */
    public static final String SQL_COL_NAME_VACUUMCHECKVALUEMB = "vacuum_check_value_mb_S";
    

    /** Generated property name */
    public static final String PROP_NAME_VINNO = "vinno";

    /** Generated column name */
    public static final String SQL_COL_NAME_VINNO = "vin_no_S";
    

    /** Generated property name */
    public static final String PROP_NAME_VOLUMEMASSVALUE = "volumemassvalue";

    /** Generated column name */
    public static final String SQL_COL_NAME_VOLUMEMASSVALUE = "volume_mass_value_S";
    
    /**
     * Generated getter for column cycle_fault.
     * Column description: 
     *
     * @return the requested value
     */
    public String getCyclefault();

    /**
     * Generated setter for column cycle_fault.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setCyclefault(String value);

    /**
     * Generated getter for column cycle_no.
     * Column description: 
     *
     * @return the requested value
     */
    public String getCycleno();

    /**
     * Generated setter for column cycle_no.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setCycleno(String value);

    /**
     * Generated getter for column cycle_result.
     * Column description: 
     *
     * @return the requested value
     */
    public String getCycleresult();

    /**
     * Generated setter for column cycle_result.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setCycleresult(String value);

    /**
     * Generated getter for column cycle_time_s.
     * Column description: 
     *
     * @return the requested value
     */
    public String getCycletimes();

    /**
     * Generated setter for column cycle_time_s.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setCycletimes(String value);

    /**
     * Generated getter for column date_time.
     * Column description: 
     *
     * @return the requested value
     */
    public String getDatetime();

    /**
     * Generated setter for column date_time.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setDatetime(String value);

    /**
     * Generated getter for column delta_differ_pressure_b.
     * Column description: 
     *
     * @return the requested value
     */
    public String getDeltadifferpressureb();

    /**
     * Generated setter for column delta_differ_pressure_b.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setDeltadifferpressureb(String value);

    /**
     * Generated getter for column delta_pressure_check_b.
     * Column description: 
     *
     * @return the requested value
     */
    public String getDeltapressurecheckb();

    /**
     * Generated setter for column delta_pressure_check_b.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setDeltapressurecheckb(String value);

    /**
     * Generated getter for column expansion_tank_volume_i.
     * Column description: 
     *
     * @return the requested value
     */
    public String getExpansiontankvolumei();

    /**
     * Generated setter for column expansion_tank_volume_i.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setExpansiontankvolumei(String value);

    /**
     * Generated getter for column filling_pressure_value_b.
     * Column description: 
     *
     * @return the requested value
     */
    public String getFillingpressurevalueb();

    /**
     * Generated setter for column filling_pressure_value_b.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setFillingpressurevalueb(String value);

    /**
     * Generated getter for column location.
     * Column description: 
     *
     * @return the requested value
     */
    public String getLocation();

    /**
     * Generated setter for column location.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setLocation(String value);

    /**
     * Generated getter for column mobile_unit_no.
     * Column description: 
     *
     * @return the requested value
     */
    public String getMobileunitno();

    /**
     * Generated setter for column mobile_unit_no.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setMobileunitno(String value);

    /**
     * Generated getter for column multi_mixing_volume_i.
     * Column description: 
     *
     * @return the requested value
     */
    public String getMultimixingvolumei();

    /**
     * Generated setter for column multi_mixing_volume_i.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setMultimixingvolumei(String value);

    /**
     * Generated getter for column pag_oil_volume_ml.
     * Column description: 
     *
     * @return the requested value
     */
    public String getPagoilvolumeml();

    /**
     * Generated setter for column pag_oil_volume_ml.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setPagoilvolumeml(String value);

    /**
     * Generated getter for column process_type.
     * Column description: 
     *
     * @return the requested value
     */
    public String getProcesstype();

    /**
     * Generated setter for column process_type.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setProcesstype(String value);

    /**
     * Generated getter for column res1.
     * Column description: 
     *
     * @return the requested value
     */
    public String getRes1();

    /**
     * Generated setter for column res1.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setRes1(String value);

    /**
     * Generated getter for column res2.
     * Column description: 
     *
     * @return the requested value
     */
    public String getRes2();

    /**
     * Generated setter for column res2.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setRes2(String value);

    /**
     * Generated getter for column res3.
     * Column description: 
     *
     * @return the requested value
     */
    public String getRes3();

    /**
     * Generated setter for column res3.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setRes3(String value);

    /**
     * Generated getter for column res4.
     * Column description: 
     *
     * @return the requested value
     */
    public String getRes4();

    /**
     * Generated setter for column res4.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setRes4(String value);

    /**
     * Generated getter for column serial_number.
     * Column description: 
     *
     * @return the requested value
     */
    public String getSerialnumber();

    /**
     * Generated setter for column serial_number.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setSerialnumber(String value);

    /**
     * Generated getter for column temperature_value_oc.
     * Column description: 
     *
     * @return the requested value
     */
    public String getTemperaturevalueoc();

    /**
     * Generated setter for column temperature_value_oc.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setTemperaturevalueoc(String value);

    /**
     * Generated getter for column test_air_residual_cl.
     * Column description: 
     *
     * @return the requested value
     */
    public String getTestairresidualcl();

    /**
     * Generated setter for column test_air_residual_cl.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setTestairresidualcl(String value);

    /**
     * Generated getter for column unity.
     * Column description: 
     *
     * @return the requested value
     */
    public String getUnity();

    /**
     * Generated setter for column unity.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setUnity(String value);

    /**
     * Generated getter for column vacuum_1_value_mb.
     * Column description: 
     *
     * @return the requested value
     */
    public String getVacuum1valuemb();

    /**
     * Generated setter for column vacuum_1_value_mb.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setVacuum1valuemb(String value);

    /**
     * Generated getter for column vacuum_check_value_mb.
     * Column description: 
     *
     * @return the requested value
     */
    public String getVacuumcheckvaluemb();

    /**
     * Generated setter for column vacuum_check_value_mb.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setVacuumcheckvaluemb(String value);

    /**
     * Generated getter for column vin_no.
     * Column description: 
     *
     * @return the requested value
     */
    public String getVinno();

    /**
     * Generated setter for column vin_no.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setVinno(String value);

    /**
     * Generated getter for column volume_mass_value.
     * Column description: 
     *
     * @return the requested value
     */
    public String getVolumemassvalue();

    /**
     * Generated setter for column volume_mass_value.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setVolumemassvalue(String value);

}
