package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMOilFillingResultFilter;

/**
 * Generated filter interface for application table AS_IM_OilFillingResult.
 * @ftps.exclude 
 */
public interface IMESASIMOilFillingResultFilter extends IMESGeneratedASIMOilFillingResultFilter {
}
