// CHECKSTYLE:FileLength:off (reason:generated)
// CHECKSTYLE:LineLength:off (reason:generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import java.util.List;

import com.datasweep.compatibility.client.DatasweepException;
import com.rockwell.mes.commons.base.ifc.objects.IMESATObjectFilter;

import ... tbd ... // TODO Please specify package name.IMESASIMOilFillingResult;
import ... tbd ... // TODO Please specify package name.IMESASIMOilFillingResultFilter;


/**
 * Generated filter interface for application table AS_IM_OilFillingResult.
 * @ftps.exclude 
 */
public interface IMESGeneratedASIMOilFillingResultFilter extends IMESATObjectFilter  {

    /**
     * Generated method definition
     *
     * @return the list of the objects
     */
    public List<IMESASIMOilFillingResult> getFilteredObjects();

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forCyclefaultContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forCyclefaultEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forCyclefaultNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forCyclefaultStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forCyclenoContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forCyclenoEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forCyclenoNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forCyclenoStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forCycleresultContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forCycleresultEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forCycleresultNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forCycleresultStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forCycletimesContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forCycletimesEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forCycletimesNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forCycletimesStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forDatetimeContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forDatetimeEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forDatetimeNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forDatetimeStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forDeltadifferpressurebContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forDeltadifferpressurebEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forDeltadifferpressurebNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forDeltadifferpressurebStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forDeltapressurecheckbContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forDeltapressurecheckbEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forDeltapressurecheckbNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forDeltapressurecheckbStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forExpansiontankvolumeiContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forExpansiontankvolumeiEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forExpansiontankvolumeiNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forExpansiontankvolumeiStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forFillingpressurevaluebContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forFillingpressurevaluebEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forFillingpressurevaluebNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forFillingpressurevaluebStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forLocationContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forLocationEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forLocationNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forLocationStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forMobileunitnoContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forMobileunitnoEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forMobileunitnoNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forMobileunitnoStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forMultimixingvolumeiContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forMultimixingvolumeiEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forMultimixingvolumeiNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forMultimixingvolumeiStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forPagoilvolumemlContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forPagoilvolumemlEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forPagoilvolumemlNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forPagoilvolumemlStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forProcesstypeContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forProcesstypeEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forProcesstypeNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forProcesstypeStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forRes1Containing(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forRes1EqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forRes1NotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forRes1StartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forRes2Containing(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forRes2EqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forRes2NotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forRes2StartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forRes3Containing(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forRes3EqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forRes3NotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forRes3StartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forRes4Containing(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forRes4EqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forRes4NotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forRes4StartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forSerialnumberContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forSerialnumberEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forSerialnumberNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forSerialnumberStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forTemperaturevalueocContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forTemperaturevalueocEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forTemperaturevalueocNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forTemperaturevalueocStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forTestairresidualclContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forTestairresidualclEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forTestairresidualclNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forTestairresidualclStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forUnityContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forUnityEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forUnityNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forUnityStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forVacuum1valuembContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forVacuum1valuembEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forVacuum1valuembNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forVacuum1valuembStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forVacuumcheckvaluembContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forVacuumcheckvaluembEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forVacuumcheckvaluembNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forVacuumcheckvaluembStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forVinnoContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forVinnoEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forVinnoNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forVinnoStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forVolumemassvalueContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forVolumemassvalueEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forVolumemassvalueNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASIMOilFillingResultFilter forVolumemassvalueStartingWith(String value) throws DatasweepException;
}
