package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.Server;

import ... tbd ... // TODO Please specify package name.IMESASOMOilFillingResultFilter;
import ... tbd ... // TODO Please specify package name.MESGeneratedASOMOilFillingResultFilter;

/**
 * Generated filter class for application table AS_OM_OilFillingResult.
 */
public class MESASOMOilFillingResultFilter extends MESGeneratedASOMOilFillingResultFilter //nl
                                              implements IMESASOMOilFillingResultFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESASOMOilFillingResultFilter(Server server) {
        super(server);
    }

    /**
     * Generated default constructor
     */
    public MESASOMOilFillingResultFilter() {
        super();
    }
}
