package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.ATRow;

import ... tbd ... // TODO Please specify package name.IMESASIMOilFillingResult;
import ... tbd ... // TODO Please specify package name.MESGeneratedASIMOilFillingResult;

/**
 * Generated class definition for application table AS_IM_OilFillingResult.
 * Application table description: null
 */
public class MESASIMOilFillingResult extends MESGeneratedASIMOilFillingResult //nl
                                        implements IMESASIMOilFillingResult {

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESASIMOilFillingResult(long key) {
        super(key);
    }

    /**
     * Generated constructor
     *
     * @param source the source to copy.
     */
    public MESASIMOilFillingResult(MESASIMOilFillingResult source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESASIMOilFillingResult(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESASIMOilFillingResult() {
        super();
    }

}
