package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.ATRow;

import ... tbd ... // TODO Please specify package name.IMESASOMOilFillingResult;
import ... tbd ... // TODO Please specify package name.MESGeneratedASOMOilFillingResult;

/**
 * Generated class definition for application table AS_OM_OilFillingResult.
 * Application table description: null
 */
public class MESASOMOilFillingResult extends MESGeneratedASOMOilFillingResult //nl
                                        implements IMESASOMOilFillingResult {

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESASOMOilFillingResult(long key) {
        super(key);
    }

    /**
     * Generated constructor
     *
     * @param source the source to copy.
     */
    public MESASOMOilFillingResult(MESASOMOilFillingResult source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESASOMOilFillingResult(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESASOMOilFillingResult() {
        super();
    }

}
