// CHECKSTYLE:FileLength:off (reason: generated)
// CHECKSTYLE:LineLength:off (reason: generated)
// CHECKSTYLE:MethodLength:off (reason: generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file is generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
 
import java.util.List;
 
import com.datasweep.compatibility.client.ATRow; 
import com.datasweep.compatibility.client.AccessPrivilege;
import com.datasweep.compatibility.client.DatasweepException;
import com.datasweep.compatibility.client.Response;
import com.datasweep.compatibility.client.Server;
import com.datasweep.compatibility.ui.Time;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;

import ... tbd ... // TODO Please specify package name.IMESASIMWeighingDetection;
import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMWeighingDetection;
import ... tbd ... // TODO Please specify package name.MESASIMWeighingDetection;
import ... tbd ... // TODO Please specify package name.MESASIMWeighingDetectionFilter;


/**
 * Generated class definition for application table AS_IM_WeighingDetection.
 * Application table description: null
 */
public class MESGeneratedASIMWeighingDetection extends MESATObject //nl
                                                 implements IMESGeneratedASIMWeighingDetection {


    /** Generated column name */
    public static final String COL_NAME_ZLINENO = "zlineno";

    /** Generated column name */
    public static final String COL_NAME_ZOVERALLRESULT = "zoverallresult";

    /** Generated column name */
    public static final String COL_NAME_ZPLANT = "zplant";

    /** Generated column name */
    public static final String COL_NAME_ZVIN = "zvin";

    /** Generated column name */
    public static final String COL_NAME_ZWEIGHTFA = "zweightfa";

    /** Generated column name */
    public static final String COL_NAME_ZWEIGHTFL = "zweightfl";

    /** Generated column name */
    public static final String COL_NAME_ZWEIGHTFR = "zweightfr";

    /** Generated column name */
    public static final String COL_NAME_ZWEIGHTRA = "zweightra";

    /** Generated column name */
    public static final String COL_NAME_ZWEIGHTRL = "zweightrl";

    /** Generated column name */
    public static final String COL_NAME_ZWEIGHTRR = "zweightrr";

    @Override
    public String getATDefinitionName() {
        return ATDEFINITION_NAME;
    }
    
    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESGeneratedASIMWeighingDetection(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     *
     * @param source The source to copy.
     */
    public MESGeneratedASIMWeighingDetection(MESGeneratedASIMWeighingDetection source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESGeneratedASIMWeighingDetection(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESGeneratedASIMWeighingDetection() {
        super();
    }

    /**
     * Generated method definition
     *
     * @param server The Server object
     * @return the filter object
     */
    public static MESASIMWeighingDetectionFilter createFilter(Server server) {
        return new MESASIMWeighingDetectionFilter(server);
    }

    /**
     * Generated method definition
     *
     * @return the filter object
     */
    public static MESASIMWeighingDetectionFilter createFilter() {
        return new MESASIMWeighingDetectionFilter();
    }

    /**
     * Generated method definition
     *
     * @param filter the Filter object
     * @return the list of the objects
     */
    public static List<IMESASIMWeighingDetection> getFilteredObjects(MESASIMWeighingDetectionFilter filter) {
        return MESATObject.getFilteredMESATObjectList(filter, MESASIMWeighingDetection.class);
    }

    @Override
    public boolean refresh() {
        boolean ok = super.refresh();
        if (!ok) {
            return false;
        }
        
        return true;
    }    

    @Override
    public String getZlineno() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZLINENO);
    }

    @Override
    public void setZlineno(String value) {
        String oldValue = this.getZlineno();
        this.dgtATRow.setValue(COL_NAME_ZLINENO, value);
        pcs.firePropertyChange(PROP_NAME_ZLINENO, oldValue, value);
    }

    @Override
    public String getZoverallresult() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZOVERALLRESULT);
    }

    @Override
    public void setZoverallresult(String value) {
        String oldValue = this.getZoverallresult();
        this.dgtATRow.setValue(COL_NAME_ZOVERALLRESULT, value);
        pcs.firePropertyChange(PROP_NAME_ZOVERALLRESULT, oldValue, value);
    }

    @Override
    public String getZplant() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZPLANT);
    }

    @Override
    public void setZplant(String value) {
        String oldValue = this.getZplant();
        this.dgtATRow.setValue(COL_NAME_ZPLANT, value);
        pcs.firePropertyChange(PROP_NAME_ZPLANT, oldValue, value);
    }

    @Override
    public String getZvin() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZVIN);
    }

    @Override
    public void setZvin(String value) {
        String oldValue = this.getZvin();
        this.dgtATRow.setValue(COL_NAME_ZVIN, value);
        pcs.firePropertyChange(PROP_NAME_ZVIN, oldValue, value);
    }

    @Override
    public String getZweightfa() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZWEIGHTFA);
    }

    @Override
    public void setZweightfa(String value) {
        String oldValue = this.getZweightfa();
        this.dgtATRow.setValue(COL_NAME_ZWEIGHTFA, value);
        pcs.firePropertyChange(PROP_NAME_ZWEIGHTFA, oldValue, value);
    }

    @Override
    public String getZweightfl() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZWEIGHTFL);
    }

    @Override
    public void setZweightfl(String value) {
        String oldValue = this.getZweightfl();
        this.dgtATRow.setValue(COL_NAME_ZWEIGHTFL, value);
        pcs.firePropertyChange(PROP_NAME_ZWEIGHTFL, oldValue, value);
    }

    @Override
    public String getZweightfr() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZWEIGHTFR);
    }

    @Override
    public void setZweightfr(String value) {
        String oldValue = this.getZweightfr();
        this.dgtATRow.setValue(COL_NAME_ZWEIGHTFR, value);
        pcs.firePropertyChange(PROP_NAME_ZWEIGHTFR, oldValue, value);
    }

    @Override
    public String getZweightra() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZWEIGHTRA);
    }

    @Override
    public void setZweightra(String value) {
        String oldValue = this.getZweightra();
        this.dgtATRow.setValue(COL_NAME_ZWEIGHTRA, value);
        pcs.firePropertyChange(PROP_NAME_ZWEIGHTRA, oldValue, value);
    }

    @Override
    public String getZweightrl() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZWEIGHTRL);
    }

    @Override
    public void setZweightrl(String value) {
        String oldValue = this.getZweightrl();
        this.dgtATRow.setValue(COL_NAME_ZWEIGHTRL, value);
        pcs.firePropertyChange(PROP_NAME_ZWEIGHTRL, oldValue, value);
    }

    @Override
    public String getZweightrr() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZWEIGHTRR);
    }

    @Override
    public void setZweightrr(String value) {
        String oldValue = this.getZweightrr();
        this.dgtATRow.setValue(COL_NAME_ZWEIGHTRR, value);
        pcs.firePropertyChange(PROP_NAME_ZWEIGHTRR, oldValue, value);
    }

    // CHECKSTYLE:MethodNameCheck:off
    @Override
    public void Save(Time time, String comment, AccessPrivilege accessPrivilege) throws DatasweepException {
        // Check if attached reference is valid:
        Response res = new Response();
        if (res.isError()) {
            throw new DatasweepException(res);
        }
        // okay, save here.
        super.Save(time, comment, accessPrivilege);
    }
     // CHECKSTYLE:MethodNameCheck:on
     
}
