package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMTorqueResultFilter;

/**
 * Generated filter interface for application table AS_IM_TorqueResult.
 * @ftps.exclude 
 */
public interface IMESASIMTorqueResultFilter extends IMESGeneratedASIMTorqueResultFilter {
}
