package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.Server;

import ... tbd ... // TODO Please specify package name.IMESASIMTorqueResultFilter;
import ... tbd ... // TODO Please specify package name.MESGeneratedASIMTorqueResultFilter;

/**
 * Generated filter class for application table AS_IM_TorqueResult.
 */
public class MESASIMTorqueResultFilter extends MESGeneratedASIMTorqueResultFilter //nl
                                              implements IMESASIMTorqueResultFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESASIMTorqueResultFilter(Server server) {
        super(server);
    }

    /**
     * Generated default constructor
     */
    public MESASIMTorqueResultFilter() {
        super();
    }
}
