package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.Server;

import ... tbd ... // TODO Please specify package name.IMESASIMDeviceMperationModeFilter;
import ... tbd ... // TODO Please specify package name.MESGeneratedASIMDeviceMperationModeFilter;

/**
 * Generated filter class for application table AS_IM_DeviceMperationMode.
 */
public class MESASIMDeviceMperationModeFilter extends MESGeneratedASIMDeviceMperationModeFilter //nl
                                              implements IMESASIMDeviceMperationModeFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESASIMDeviceMperationModeFilter(Server server) {
        super(server);
    }

    /**
     * Generated default constructor
     */
    public MESASIMDeviceMperationModeFilter() {
        super();
    }
}
