// CHECKSTYLE:FileLength:off (reason: generated)
// CHECKSTYLE:LineLength:off (reason: generated)
// CHECKSTYLE:MethodLength:off (reason: generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file is generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
 
import java.util.List;
 
import com.datasweep.compatibility.client.ATRow; 
import com.datasweep.compatibility.client.AccessPrivilege;
import com.datasweep.compatibility.client.DatasweepException;
import com.datasweep.compatibility.client.Response;
import com.datasweep.compatibility.client.Server;
import com.datasweep.compatibility.ui.Time;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;

import ... tbd ... // TODO Please specify package name.IMESASIMDeviceMperationMode;
import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMDeviceMperationMode;
import ... tbd ... // TODO Please specify package name.MESASIMDeviceMperationMode;
import ... tbd ... // TODO Please specify package name.MESASIMDeviceMperationModeFilter;


/**
 * Generated class definition for application table AS_IM_DeviceMperationMode.
 * Application table description: null
 */
public class MESGeneratedASIMDeviceMperationMode extends MESATObject //nl
                                                 implements IMESGeneratedASIMDeviceMperationMode {


    /** Generated column name */
    public static final String COL_NAME_ZEQUIPNO = "zequipno";

    /** Generated column name */
    public static final String COL_NAME_ZLINENO = "zlineno";

    /** Generated column name */
    public static final String COL_NAME_ZMODE = "zmode";

    /** Generated column name */
    public static final String COL_NAME_ZPLANT = "zplant";

    @Override
    public String getATDefinitionName() {
        return ATDEFINITION_NAME;
    }
    
    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESGeneratedASIMDeviceMperationMode(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     *
     * @param source The source to copy.
     */
    public MESGeneratedASIMDeviceMperationMode(MESGeneratedASIMDeviceMperationMode source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESGeneratedASIMDeviceMperationMode(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESGeneratedASIMDeviceMperationMode() {
        super();
    }

    /**
     * Generated method definition
     *
     * @param server The Server object
     * @return the filter object
     */
    public static MESASIMDeviceMperationModeFilter createFilter(Server server) {
        return new MESASIMDeviceMperationModeFilter(server);
    }

    /**
     * Generated method definition
     *
     * @return the filter object
     */
    public static MESASIMDeviceMperationModeFilter createFilter() {
        return new MESASIMDeviceMperationModeFilter();
    }

    /**
     * Generated method definition
     *
     * @param filter the Filter object
     * @return the list of the objects
     */
    public static List<IMESASIMDeviceMperationMode> getFilteredObjects(MESASIMDeviceMperationModeFilter filter) {
        return MESATObject.getFilteredMESATObjectList(filter, MESASIMDeviceMperationMode.class);
    }

    @Override
    public boolean refresh() {
        boolean ok = super.refresh();
        if (!ok) {
            return false;
        }
        
        return true;
    }    

    @Override
    public String getZequipno() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZEQUIPNO);
    }

    @Override
    public void setZequipno(String value) {
        String oldValue = this.getZequipno();
        this.dgtATRow.setValue(COL_NAME_ZEQUIPNO, value);
        pcs.firePropertyChange(PROP_NAME_ZEQUIPNO, oldValue, value);
    }

    @Override
    public String getZlineno() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZLINENO);
    }

    @Override
    public void setZlineno(String value) {
        String oldValue = this.getZlineno();
        this.dgtATRow.setValue(COL_NAME_ZLINENO, value);
        pcs.firePropertyChange(PROP_NAME_ZLINENO, oldValue, value);
    }

    @Override
    public String getZmode() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZMODE);
    }

    @Override
    public void setZmode(String value) {
        String oldValue = this.getZmode();
        this.dgtATRow.setValue(COL_NAME_ZMODE, value);
        pcs.firePropertyChange(PROP_NAME_ZMODE, oldValue, value);
    }

    @Override
    public String getZplant() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZPLANT);
    }

    @Override
    public void setZplant(String value) {
        String oldValue = this.getZplant();
        this.dgtATRow.setValue(COL_NAME_ZPLANT, value);
        pcs.firePropertyChange(PROP_NAME_ZPLANT, oldValue, value);
    }

    // CHECKSTYLE:MethodNameCheck:off
    @Override
    public void Save(Time time, String comment, AccessPrivilege accessPrivilege) throws DatasweepException {
        // Check if attached reference is valid:
        Response res = new Response();
        if (res.isError()) {
            throw new DatasweepException(res);
        }
        // okay, save here.
        super.Save(time, comment, accessPrivilege);
    }
     // CHECKSTYLE:MethodNameCheck:on
     
}
