// CHECKSTYLE:FileLength:off (reason: generated)
// CHECKSTYLE:LineLength:off (reason: generated)
// CHECKSTYLE:MethodLength:off (reason: generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import java.util.List;

import com.datasweep.compatibility.client.ATRowFilter;
import com.datasweep.compatibility.client.DatasweepException;
import com.datasweep.compatibility.client.Server;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;
import com.rockwell.mes.commons.base.ifc.services.PCContext;

import ... tbd ... // TODO Please specify package name.IMESASIMDeviceMperationMode;
import ... tbd ... // TODO Please specify package name.IMESASIMDeviceMperationModeFilter;
import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMDeviceMperationModeFilter;
import ... tbd ... // TODO Please specify package name.MESASIMDeviceMperationMode;


/**
 * Generated filter class for application table AS_IM_DeviceMperationMode.
 */
public class MESGeneratedASIMDeviceMperationModeFilter extends ATRowFilter implements IMESGeneratedASIMDeviceMperationModeFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /** Generated attribute definition */
    protected static final String ATDEFINITION_NAME = "AS_IM_DeviceMperationMode";

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESGeneratedASIMDeviceMperationModeFilter(Server server) {
        super(server, ATDEFINITION_NAME);
    }

    /**
     * Generated default constructor
     */
    public MESGeneratedASIMDeviceMperationModeFilter() {
        this(PCContext.getServerImpl());
    }

    @Override
    public List<IMESASIMDeviceMperationMode> getFilteredObjects() {
        return MESATObject.getFilteredMESATObjectList(this, MESASIMDeviceMperationMode.class);
    }

    @Override
    public IMESASIMDeviceMperationModeFilter forZequipnoContaining(String value) throws DatasweepException {
        return (IMESASIMDeviceMperationModeFilter) forColumnNameContaining(MESGeneratedASIMDeviceMperationMode.COL_NAME_ZEQUIPNO, value);
    }
    @Override
    public IMESASIMDeviceMperationModeFilter forZequipnoEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceMperationModeFilter) forColumnNameEqualTo(MESGeneratedASIMDeviceMperationMode.COL_NAME_ZEQUIPNO, value);
    }
    @Override
    public IMESASIMDeviceMperationModeFilter forZequipnoNotEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceMperationModeFilter) forColumnNameNotEqualTo(MESGeneratedASIMDeviceMperationMode.COL_NAME_ZEQUIPNO, value);
    }
    @Override
    public IMESASIMDeviceMperationModeFilter forZequipnoStartingWith(String value) throws DatasweepException {
        return (IMESASIMDeviceMperationModeFilter) forColumnNameStartingWith(MESGeneratedASIMDeviceMperationMode.COL_NAME_ZEQUIPNO, value);
    }
    @Override
    public IMESASIMDeviceMperationModeFilter forZlinenoContaining(String value) throws DatasweepException {
        return (IMESASIMDeviceMperationModeFilter) forColumnNameContaining(MESGeneratedASIMDeviceMperationMode.COL_NAME_ZLINENO, value);
    }
    @Override
    public IMESASIMDeviceMperationModeFilter forZlinenoEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceMperationModeFilter) forColumnNameEqualTo(MESGeneratedASIMDeviceMperationMode.COL_NAME_ZLINENO, value);
    }
    @Override
    public IMESASIMDeviceMperationModeFilter forZlinenoNotEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceMperationModeFilter) forColumnNameNotEqualTo(MESGeneratedASIMDeviceMperationMode.COL_NAME_ZLINENO, value);
    }
    @Override
    public IMESASIMDeviceMperationModeFilter forZlinenoStartingWith(String value) throws DatasweepException {
        return (IMESASIMDeviceMperationModeFilter) forColumnNameStartingWith(MESGeneratedASIMDeviceMperationMode.COL_NAME_ZLINENO, value);
    }
    @Override
    public IMESASIMDeviceMperationModeFilter forZmodeContaining(String value) throws DatasweepException {
        return (IMESASIMDeviceMperationModeFilter) forColumnNameContaining(MESGeneratedASIMDeviceMperationMode.COL_NAME_ZMODE, value);
    }
    @Override
    public IMESASIMDeviceMperationModeFilter forZmodeEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceMperationModeFilter) forColumnNameEqualTo(MESGeneratedASIMDeviceMperationMode.COL_NAME_ZMODE, value);
    }
    @Override
    public IMESASIMDeviceMperationModeFilter forZmodeNotEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceMperationModeFilter) forColumnNameNotEqualTo(MESGeneratedASIMDeviceMperationMode.COL_NAME_ZMODE, value);
    }
    @Override
    public IMESASIMDeviceMperationModeFilter forZmodeStartingWith(String value) throws DatasweepException {
        return (IMESASIMDeviceMperationModeFilter) forColumnNameStartingWith(MESGeneratedASIMDeviceMperationMode.COL_NAME_ZMODE, value);
    }
    @Override
    public IMESASIMDeviceMperationModeFilter forZplantContaining(String value) throws DatasweepException {
        return (IMESASIMDeviceMperationModeFilter) forColumnNameContaining(MESGeneratedASIMDeviceMperationMode.COL_NAME_ZPLANT, value);
    }
    @Override
    public IMESASIMDeviceMperationModeFilter forZplantEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceMperationModeFilter) forColumnNameEqualTo(MESGeneratedASIMDeviceMperationMode.COL_NAME_ZPLANT, value);
    }
    @Override
    public IMESASIMDeviceMperationModeFilter forZplantNotEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceMperationModeFilter) forColumnNameNotEqualTo(MESGeneratedASIMDeviceMperationMode.COL_NAME_ZPLANT, value);
    }
    @Override
    public IMESASIMDeviceMperationModeFilter forZplantStartingWith(String value) throws DatasweepException {
        return (IMESASIMDeviceMperationModeFilter) forColumnNameStartingWith(MESGeneratedASIMDeviceMperationMode.COL_NAME_ZPLANT, value);
    }
}
