package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.Server;

import ... tbd ... // TODO Please specify package name.IMESASIMVehicleNamePlateFilter;
import ... tbd ... // TODO Please specify package name.MESGeneratedASIMVehicleNamePlateFilter;

/**
 * Generated filter class for application table AS_IM_VehicleNamePlate.
 */
public class MESASIMVehicleNamePlateFilter extends MESGeneratedASIMVehicleNamePlateFilter //nl
                                              implements IMESASIMVehicleNamePlateFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESASIMVehicleNamePlateFilter(Server server) {
        super(server);
    }

    /**
     * Generated default constructor
     */
    public MESASIMVehicleNamePlateFilter() {
        super();
    }
}
