package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.Server;

import ... tbd ... // TODO Please specify package name.IMESASIMObdDetectionFilter;
import ... tbd ... // TODO Please specify package name.MESGeneratedASIMObdDetectionFilter;

/**
 * Generated filter class for application table AS_IM_ObdDetection.
 */
public class MESASIMObdDetectionFilter extends MESGeneratedASIMObdDetectionFilter //nl
                                              implements IMESASIMObdDetectionFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESASIMObdDetectionFilter(Server server) {
        super(server);
    }

    /**
     * Generated default constructor
     */
    public MESASIMObdDetectionFilter() {
        super();
    }
}
