// CHECKSTYLE:FileLength:off (reason: generated)
// CHECKSTYLE:LineLength:off (reason: generated)
// CHECKSTYLE:MethodLength:off (reason: generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file is generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
 
import java.util.List;
 
import com.datasweep.compatibility.client.ATRow; 
import com.datasweep.compatibility.client.AccessPrivilege;
import com.datasweep.compatibility.client.DatasweepException;
import com.datasweep.compatibility.client.Response;
import com.datasweep.compatibility.client.Server;
import com.datasweep.compatibility.ui.Time;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;

import ... tbd ... // TODO Please specify package name.IMESASIMObdDetection;
import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMObdDetection;
import ... tbd ... // TODO Please specify package name.MESASIMObdDetection;
import ... tbd ... // TODO Please specify package name.MESASIMObdDetectionFilter;


/**
 * Generated class definition for application table AS_IM_ObdDetection.
 * Application table description: null
 */
public class MESGeneratedASIMObdDetection extends MESATObject //nl
                                                 implements IMESGeneratedASIMObdDetection {


    /** Generated column name */
    public static final String COL_NAME_APASS = "apass";

    /** Generated column name */
    public static final String COL_NAME_CALID = "calid";

    /** Generated column name */
    public static final String COL_NAME_CVN = "cvn";

    /** Generated column name */
    public static final String COL_NAME_JCXTNO = "jcxtno";

    /** Generated column name */
    public static final String COL_NAME_MODULEID = "moduleid";

    /** Generated column name */
    public static final String COL_NAME_OBD = "obd";

    /** Generated column name */
    public static final String COL_NAME_ODO = "odo";

    /** Generated column name */
    public static final String COL_NAME_OPASS = "opass";

    /** Generated column name */
    public static final String COL_NAME_OTESTDATE = "otestdate";

    /** Generated column name */
    public static final String COL_NAME_RESULT = "result";

    /** Generated column name */
    public static final String COL_NAME_VIN = "vin";

    /** Generated column name */
    public static final String COL_NAME_ZLINENO = "zlineno";

    /** Generated column name */
    public static final String COL_NAME_ZPLANT = "zplant";

    @Override
    public String getATDefinitionName() {
        return ATDEFINITION_NAME;
    }
    
    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESGeneratedASIMObdDetection(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     *
     * @param source The source to copy.
     */
    public MESGeneratedASIMObdDetection(MESGeneratedASIMObdDetection source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESGeneratedASIMObdDetection(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESGeneratedASIMObdDetection() {
        super();
    }

    /**
     * Generated method definition
     *
     * @param server The Server object
     * @return the filter object
     */
    public static MESASIMObdDetectionFilter createFilter(Server server) {
        return new MESASIMObdDetectionFilter(server);
    }

    /**
     * Generated method definition
     *
     * @return the filter object
     */
    public static MESASIMObdDetectionFilter createFilter() {
        return new MESASIMObdDetectionFilter();
    }

    /**
     * Generated method definition
     *
     * @param filter the Filter object
     * @return the list of the objects
     */
    public static List<IMESASIMObdDetection> getFilteredObjects(MESASIMObdDetectionFilter filter) {
        return MESATObject.getFilteredMESATObjectList(filter, MESASIMObdDetection.class);
    }

    @Override
    public boolean refresh() {
        boolean ok = super.refresh();
        if (!ok) {
            return false;
        }
        
        return true;
    }    

    @Override
    public String getApass() {
        return (String) this.dgtATRow.getValue(COL_NAME_APASS);
    }

    @Override
    public void setApass(String value) {
        String oldValue = this.getApass();
        this.dgtATRow.setValue(COL_NAME_APASS, value);
        pcs.firePropertyChange(PROP_NAME_APASS, oldValue, value);
    }

    @Override
    public String getCalid() {
        return (String) this.dgtATRow.getValue(COL_NAME_CALID);
    }

    @Override
    public void setCalid(String value) {
        String oldValue = this.getCalid();
        this.dgtATRow.setValue(COL_NAME_CALID, value);
        pcs.firePropertyChange(PROP_NAME_CALID, oldValue, value);
    }

    @Override
    public String getCvn() {
        return (String) this.dgtATRow.getValue(COL_NAME_CVN);
    }

    @Override
    public void setCvn(String value) {
        String oldValue = this.getCvn();
        this.dgtATRow.setValue(COL_NAME_CVN, value);
        pcs.firePropertyChange(PROP_NAME_CVN, oldValue, value);
    }

    @Override
    public String getJcxtno() {
        return (String) this.dgtATRow.getValue(COL_NAME_JCXTNO);
    }

    @Override
    public void setJcxtno(String value) {
        String oldValue = this.getJcxtno();
        this.dgtATRow.setValue(COL_NAME_JCXTNO, value);
        pcs.firePropertyChange(PROP_NAME_JCXTNO, oldValue, value);
    }

    @Override
    public String getModuleid() {
        return (String) this.dgtATRow.getValue(COL_NAME_MODULEID);
    }

    @Override
    public void setModuleid(String value) {
        String oldValue = this.getModuleid();
        this.dgtATRow.setValue(COL_NAME_MODULEID, value);
        pcs.firePropertyChange(PROP_NAME_MODULEID, oldValue, value);
    }

    @Override
    public String getObd() {
        return (String) this.dgtATRow.getValue(COL_NAME_OBD);
    }

    @Override
    public void setObd(String value) {
        String oldValue = this.getObd();
        this.dgtATRow.setValue(COL_NAME_OBD, value);
        pcs.firePropertyChange(PROP_NAME_OBD, oldValue, value);
    }

    @Override
    public String getOdo() {
        return (String) this.dgtATRow.getValue(COL_NAME_ODO);
    }

    @Override
    public void setOdo(String value) {
        String oldValue = this.getOdo();
        this.dgtATRow.setValue(COL_NAME_ODO, value);
        pcs.firePropertyChange(PROP_NAME_ODO, oldValue, value);
    }

    @Override
    public String getOpass() {
        return (String) this.dgtATRow.getValue(COL_NAME_OPASS);
    }

    @Override
    public void setOpass(String value) {
        String oldValue = this.getOpass();
        this.dgtATRow.setValue(COL_NAME_OPASS, value);
        pcs.firePropertyChange(PROP_NAME_OPASS, oldValue, value);
    }

    @Override
    public String getOtestdate() {
        return (String) this.dgtATRow.getValue(COL_NAME_OTESTDATE);
    }

    @Override
    public void setOtestdate(String value) {
        String oldValue = this.getOtestdate();
        this.dgtATRow.setValue(COL_NAME_OTESTDATE, value);
        pcs.firePropertyChange(PROP_NAME_OTESTDATE, oldValue, value);
    }

    @Override
    public String getResult() {
        return (String) this.dgtATRow.getValue(COL_NAME_RESULT);
    }

    @Override
    public void setResult(String value) {
        String oldValue = this.getResult();
        this.dgtATRow.setValue(COL_NAME_RESULT, value);
        pcs.firePropertyChange(PROP_NAME_RESULT, oldValue, value);
    }

    @Override
    public String getVin() {
        return (String) this.dgtATRow.getValue(COL_NAME_VIN);
    }

    @Override
    public void setVin(String value) {
        String oldValue = this.getVin();
        this.dgtATRow.setValue(COL_NAME_VIN, value);
        pcs.firePropertyChange(PROP_NAME_VIN, oldValue, value);
    }

    @Override
    public String getZlineno() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZLINENO);
    }

    @Override
    public void setZlineno(String value) {
        String oldValue = this.getZlineno();
        this.dgtATRow.setValue(COL_NAME_ZLINENO, value);
        pcs.firePropertyChange(PROP_NAME_ZLINENO, oldValue, value);
    }

    @Override
    public String getZplant() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZPLANT);
    }

    @Override
    public void setZplant(String value) {
        String oldValue = this.getZplant();
        this.dgtATRow.setValue(COL_NAME_ZPLANT, value);
        pcs.firePropertyChange(PROP_NAME_ZPLANT, oldValue, value);
    }

    // CHECKSTYLE:MethodNameCheck:off
    @Override
    public void Save(Time time, String comment, AccessPrivilege accessPrivilege) throws DatasweepException {
        // Check if attached reference is valid:
        Response res = new Response();
        if (res.isError()) {
            throw new DatasweepException(res);
        }
        // okay, save here.
        super.Save(time, comment, accessPrivilege);
    }
     // CHECKSTYLE:MethodNameCheck:on
     
}
