package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.ATRow;

import ... tbd ... // TODO Please specify package name.IMESASIMCLOverallAppraisal;
import ... tbd ... // TODO Please specify package name.MESGeneratedASIMCLOverallAppraisal;

/**
 * Generated class definition for application table AS_IM_CL_OverallAppraisal.
 * Application table description: null
 */
public class MESASIMCLOverallAppraisal extends MESGeneratedASIMCLOverallAppraisal //nl
                                        implements IMESASIMCLOverallAppraisal {

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESASIMCLOverallAppraisal(long key) {
        super(key);
    }

    /**
     * Generated constructor
     *
     * @param source the source to copy.
     */
    public MESASIMCLOverallAppraisal(MESASIMCLOverallAppraisal source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESASIMCLOverallAppraisal(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESASIMCLOverallAppraisal() {
        super();
    }

}
