// CHECKSTYLE:FileLength:off (reason: generated)
// CHECKSTYLE:LineLength:off (reason: generated)
// CHECKSTYLE:MethodLength:off (reason: generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file is generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
 
import java.util.List;
 
import com.datasweep.compatibility.client.ATRow; 
import com.datasweep.compatibility.client.AccessPrivilege;
import com.datasweep.compatibility.client.DatasweepException;
import com.datasweep.compatibility.client.Response;
import com.datasweep.compatibility.client.Server;
import com.datasweep.compatibility.ui.Time;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;

import ... tbd ... // TODO Please specify package name.IMESASIMCLOverallAppraisal;
import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMCLOverallAppraisal;
import ... tbd ... // TODO Please specify package name.MESASIMCLOverallAppraisal;
import ... tbd ... // TODO Please specify package name.MESASIMCLOverallAppraisalFilter;


/**
 * Generated class definition for application table AS_IM_CL_OverallAppraisal.
 * Application table description: null
 */
public class MESGeneratedASIMCLOverallAppraisal extends MESATObject //nl
                                                 implements IMESGeneratedASIMCLOverallAppraisal {


    /** Generated column name */
    public static final String COL_NAME_ZLINENO = "zlineno";

    /** Generated column name */
    public static final String COL_NAME_ZOVERALLRESULT = "zoverallresult";

    /** Generated column name */
    public static final String COL_NAME_ZPLANT = "zplant";

    /** Generated column name */
    public static final String COL_NAME_ZVIN = "zvin";

    @Override
    public String getATDefinitionName() {
        return ATDEFINITION_NAME;
    }
    
    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESGeneratedASIMCLOverallAppraisal(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     *
     * @param source The source to copy.
     */
    public MESGeneratedASIMCLOverallAppraisal(MESGeneratedASIMCLOverallAppraisal source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESGeneratedASIMCLOverallAppraisal(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESGeneratedASIMCLOverallAppraisal() {
        super();
    }

    /**
     * Generated method definition
     *
     * @param server The Server object
     * @return the filter object
     */
    public static MESASIMCLOverallAppraisalFilter createFilter(Server server) {
        return new MESASIMCLOverallAppraisalFilter(server);
    }

    /**
     * Generated method definition
     *
     * @return the filter object
     */
    public static MESASIMCLOverallAppraisalFilter createFilter() {
        return new MESASIMCLOverallAppraisalFilter();
    }

    /**
     * Generated method definition
     *
     * @param filter the Filter object
     * @return the list of the objects
     */
    public static List<IMESASIMCLOverallAppraisal> getFilteredObjects(MESASIMCLOverallAppraisalFilter filter) {
        return MESATObject.getFilteredMESATObjectList(filter, MESASIMCLOverallAppraisal.class);
    }

    @Override
    public boolean refresh() {
        boolean ok = super.refresh();
        if (!ok) {
            return false;
        }
        
        return true;
    }    

    @Override
    public String getZlineno() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZLINENO);
    }

    @Override
    public void setZlineno(String value) {
        String oldValue = this.getZlineno();
        this.dgtATRow.setValue(COL_NAME_ZLINENO, value);
        pcs.firePropertyChange(PROP_NAME_ZLINENO, oldValue, value);
    }

    @Override
    public String getZoverallresult() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZOVERALLRESULT);
    }

    @Override
    public void setZoverallresult(String value) {
        String oldValue = this.getZoverallresult();
        this.dgtATRow.setValue(COL_NAME_ZOVERALLRESULT, value);
        pcs.firePropertyChange(PROP_NAME_ZOVERALLRESULT, oldValue, value);
    }

    @Override
    public String getZplant() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZPLANT);
    }

    @Override
    public void setZplant(String value) {
        String oldValue = this.getZplant();
        this.dgtATRow.setValue(COL_NAME_ZPLANT, value);
        pcs.firePropertyChange(PROP_NAME_ZPLANT, oldValue, value);
    }

    @Override
    public String getZvin() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZVIN);
    }

    @Override
    public void setZvin(String value) {
        String oldValue = this.getZvin();
        this.dgtATRow.setValue(COL_NAME_ZVIN, value);
        pcs.firePropertyChange(PROP_NAME_ZVIN, oldValue, value);
    }

    // CHECKSTYLE:MethodNameCheck:off
    @Override
    public void Save(Time time, String comment, AccessPrivilege accessPrivilege) throws DatasweepException {
        // Check if attached reference is valid:
        Response res = new Response();
        if (res.isError()) {
            throw new DatasweepException(res);
        }
        // okay, save here.
        super.Save(time, comment, accessPrivilege);
    }
     // CHECKSTYLE:MethodNameCheck:on
     
}
