// CHECKSTYLE:FileLength:off (reason: generated)
// CHECKSTYLE:LineLength:off (reason: generated)
// CHECKSTYLE:MethodLength:off (reason: generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import java.util.List;

import com.datasweep.compatibility.client.ATRowFilter;
import com.datasweep.compatibility.client.DatasweepException;
import com.datasweep.compatibility.client.Server;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;
import com.rockwell.mes.commons.base.ifc.services.PCContext;

import ... tbd ... // TODO Please specify package name.IMESASIMDeviceStatusPut;
import ... tbd ... // TODO Please specify package name.IMESASIMDeviceStatusPutFilter;
import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMDeviceStatusPutFilter;
import ... tbd ... // TODO Please specify package name.MESASIMDeviceStatusPut;


/**
 * Generated filter class for application table AS_IM_DeviceStatusPut.
 */
public class MESGeneratedASIMDeviceStatusPutFilter extends ATRowFilter implements IMESGeneratedASIMDeviceStatusPutFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /** Generated attribute definition */
    protected static final String ATDEFINITION_NAME = "AS_IM_DeviceStatusPut";

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESGeneratedASIMDeviceStatusPutFilter(Server server) {
        super(server, ATDEFINITION_NAME);
    }

    /**
     * Generated default constructor
     */
    public MESGeneratedASIMDeviceStatusPutFilter() {
        this(PCContext.getServerImpl());
    }

    @Override
    public List<IMESASIMDeviceStatusPut> getFilteredObjects() {
        return MESATObject.getFilteredMESATObjectList(this, MESASIMDeviceStatusPut.class);
    }

    @Override
    public IMESASIMDeviceStatusPutFilter forZEquipNOContaining(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameContaining(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZEQUIPNO, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZEquipNOEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameEqualTo(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZEQUIPNO, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZEquipNONotEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameNotEqualTo(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZEQUIPNO, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZEquipNOStartingWith(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameStartingWith(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZEQUIPNO, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZLineNOContaining(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameContaining(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZLINENO, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZLineNOEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameEqualTo(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZLINENO, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZLineNONotEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameNotEqualTo(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZLINENO, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZLineNOStartingWith(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameStartingWith(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZLINENO, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZPlantContaining(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameContaining(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZPLANT, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZPlantEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameEqualTo(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZPLANT, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZPlantNotEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameNotEqualTo(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZPLANT, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZPlantStartingWith(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameStartingWith(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZPLANT, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZStatusContaining(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameContaining(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZSTATUS, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZStatusEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameEqualTo(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZSTATUS, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZStatusNotEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameNotEqualTo(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZSTATUS, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZStatusStartingWith(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameStartingWith(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZSTATUS, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZStatusTimeContaining(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameContaining(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZSTATUSTIME, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZStatusTimeEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameEqualTo(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZSTATUSTIME, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZStatusTimeNotEqualTo(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameNotEqualTo(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZSTATUSTIME, value);
    }
    @Override
    public IMESASIMDeviceStatusPutFilter forZStatusTimeStartingWith(String value) throws DatasweepException {
        return (IMESASIMDeviceStatusPutFilter) forColumnNameStartingWith(MESGeneratedASIMDeviceStatusPut.COL_NAME_ZSTATUSTIME, value);
    }
}
