// CHECKSTYLE:FileLength:off (reason:generated)
// CHECKSTYLE:LineLength:off (reason:generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESATObject;


/**
 * Generated interface definition for application table AS_IM_VcatsKeyPartSNConfig.
 * Application table description: null
 * @ftps.exclude 
 */
public interface IMESGeneratedASIMVcatsKeyPartSNConfig extends IMESATObject {

    /** Generated attribute definition */
    public static final String ATDEFINITION_NAME = "AS_IM_VcatsKeyPartSNConfig";


    /** Generated property name */
    public static final String PROP_NAME_STEPCODE = "stepcode";

    /** Generated column name */
    public static final String SQL_COL_NAME_STEPCODE = "step_code_S";
    

    /** Generated property name */
    public static final String PROP_NAME_STEPNAME = "stepname";

    /** Generated column name */
    public static final String SQL_COL_NAME_STEPNAME = "step_name_S";
    

    /** Generated property name */
    public static final String PROP_NAME_VEHICLETYPE = "vehicletype";

    /** Generated column name */
    public static final String SQL_COL_NAME_VEHICLETYPE = "vehicle_type_S";
    
    /**
     * Generated getter for column step_code.
     * Column description: 
     *
     * @return the requested value
     */
    public String getStepcode();

    /**
     * Generated setter for column step_code.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setStepcode(String value);

    /**
     * Generated getter for column step_name.
     * Column description: 
     *
     * @return the requested value
     */
    public String getStepname();

    /**
     * Generated setter for column step_name.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setStepname(String value);

    /**
     * Generated getter for column vehicle_type.
     * Column description: 
     *
     * @return the requested value
     */
    public String getVehicletype();

    /**
     * Generated setter for column vehicle_type.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setVehicletype(String value);

}
