// CHECKSTYLE:FileLength:off (reason: generated)
// CHECKSTYLE:LineLength:off (reason: generated)
// CHECKSTYLE:MethodLength:off (reason: generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file is generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
 
import java.util.List;
 
import com.datasweep.compatibility.client.ATRow; 
import com.datasweep.compatibility.client.AccessPrivilege;
import com.datasweep.compatibility.client.DatasweepException;
import com.datasweep.compatibility.client.Response;
import com.datasweep.compatibility.client.Server;
import com.datasweep.compatibility.ui.Time;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;

import ... tbd ... // TODO Please specify package name.IMESASIMVcatsKeyPartSNConfig;
import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMVcatsKeyPartSNConfig;
import ... tbd ... // TODO Please specify package name.MESASIMVcatsKeyPartSNConfig;
import ... tbd ... // TODO Please specify package name.MESASIMVcatsKeyPartSNConfigFilter;


/**
 * Generated class definition for application table AS_IM_VcatsKeyPartSNConfig.
 * Application table description: null
 */
public class MESGeneratedASIMVcatsKeyPartSNConfig extends MESATObject //nl
                                                 implements IMESGeneratedASIMVcatsKeyPartSNConfig {


    /** Generated column name */
    public static final String COL_NAME_STEPCODE = "step_code";

    /** Generated column name */
    public static final String COL_NAME_STEPNAME = "step_name";

    /** Generated column name */
    public static final String COL_NAME_VEHICLETYPE = "vehicle_type";

    @Override
    public String getATDefinitionName() {
        return ATDEFINITION_NAME;
    }
    
    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESGeneratedASIMVcatsKeyPartSNConfig(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     *
     * @param source The source to copy.
     */
    public MESGeneratedASIMVcatsKeyPartSNConfig(MESGeneratedASIMVcatsKeyPartSNConfig source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESGeneratedASIMVcatsKeyPartSNConfig(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESGeneratedASIMVcatsKeyPartSNConfig() {
        super();
    }

    /**
     * Generated method definition
     *
     * @param server The Server object
     * @return the filter object
     */
    public static MESASIMVcatsKeyPartSNConfigFilter createFilter(Server server) {
        return new MESASIMVcatsKeyPartSNConfigFilter(server);
    }

    /**
     * Generated method definition
     *
     * @return the filter object
     */
    public static MESASIMVcatsKeyPartSNConfigFilter createFilter() {
        return new MESASIMVcatsKeyPartSNConfigFilter();
    }

    /**
     * Generated method definition
     *
     * @param filter the Filter object
     * @return the list of the objects
     */
    public static List<IMESASIMVcatsKeyPartSNConfig> getFilteredObjects(MESASIMVcatsKeyPartSNConfigFilter filter) {
        return MESATObject.getFilteredMESATObjectList(filter, MESASIMVcatsKeyPartSNConfig.class);
    }

    @Override
    public boolean refresh() {
        boolean ok = super.refresh();
        if (!ok) {
            return false;
        }
        
        return true;
    }    

    @Override
    public String getStepcode() {
        return (String) this.dgtATRow.getValue(COL_NAME_STEPCODE);
    }

    @Override
    public void setStepcode(String value) {
        String oldValue = this.getStepcode();
        this.dgtATRow.setValue(COL_NAME_STEPCODE, value);
        pcs.firePropertyChange(PROP_NAME_STEPCODE, oldValue, value);
    }

    @Override
    public String getStepname() {
        return (String) this.dgtATRow.getValue(COL_NAME_STEPNAME);
    }

    @Override
    public void setStepname(String value) {
        String oldValue = this.getStepname();
        this.dgtATRow.setValue(COL_NAME_STEPNAME, value);
        pcs.firePropertyChange(PROP_NAME_STEPNAME, oldValue, value);
    }

    @Override
    public String getVehicletype() {
        return (String) this.dgtATRow.getValue(COL_NAME_VEHICLETYPE);
    }

    @Override
    public void setVehicletype(String value) {
        String oldValue = this.getVehicletype();
        this.dgtATRow.setValue(COL_NAME_VEHICLETYPE, value);
        pcs.firePropertyChange(PROP_NAME_VEHICLETYPE, oldValue, value);
    }

    // CHECKSTYLE:MethodNameCheck:off
    @Override
    public void Save(Time time, String comment, AccessPrivilege accessPrivilege) throws DatasweepException {
        // Check if attached reference is valid:
        Response res = new Response();
        if (res.isError()) {
            throw new DatasweepException(res);
        }
        // okay, save here.
        super.Save(time, comment, accessPrivilege);
    }
     // CHECKSTYLE:MethodNameCheck:on
     
}
