// CHECKSTYLE:FileLength:off (reason: generated)
// CHECKSTYLE:LineLength:off (reason: generated)
// CHECKSTYLE:MethodLength:off (reason: generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file is generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
 
import java.util.List;
 
import com.datasweep.compatibility.client.ATRow; 
import com.datasweep.compatibility.client.AccessPrivilege;
import com.datasweep.compatibility.client.DatasweepException;
import com.datasweep.compatibility.client.Response;
import com.datasweep.compatibility.client.Server;
import com.datasweep.compatibility.ui.Time;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;

import ... tbd ... // TODO Please specify package name.IMESASIMClFwalignment;
import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMClFwalignment;
import ... tbd ... // TODO Please specify package name.MESASIMClFwalignment;
import ... tbd ... // TODO Please specify package name.MESASIMClFwalignmentFilter;


/**
 * Generated class definition for application table AS_IM_Cl_Fwalignment.
 * Application table description: null
 */
public class MESGeneratedASIMClFwalignment extends MESATObject //nl
                                                 implements IMESGeneratedASIMClFwalignment {


    /** Generated column name */
    public static final String COL_NAME_ZCAMBERFL = "zcamberfl";

    /** Generated column name */
    public static final String COL_NAME_ZCAMBERFLOK = "zcamberflok";

    /** Generated column name */
    public static final String COL_NAME_ZCAMBERFR = "zcamberfr";

    /** Generated column name */
    public static final String COL_NAME_ZCAMBERFROK = "zcamberfrok";

    /** Generated column name */
    public static final String COL_NAME_ZCAMBERRL = "zcamberrl";

    /** Generated column name */
    public static final String COL_NAME_ZCAMBERRLOK = "zcamberrlok";

    /** Generated column name */
    public static final String COL_NAME_ZCAMBERRR = "zcamberrr";

    /** Generated column name */
    public static final String COL_NAME_ZCAMBERRROK = "zcamberrrok";

    /** Generated column name */
    public static final String COL_NAME_ZCAMBERUNIT = "zcamberunit";

    /** Generated column name */
    public static final String COL_NAME_ZDIFFCAMBERFA = "zdiffcamberfa";

    /** Generated column name */
    public static final String COL_NAME_ZDIFFCAMBERFAOK = "zdiffcamberfaok";

    /** Generated column name */
    public static final String COL_NAME_ZDIFFCAMBERRA = "zdiffcamberra";

    /** Generated column name */
    public static final String COL_NAME_ZDIFFCAMBERRAOK = "zdiffcamberraok";

    /** Generated column name */
    public static final String COL_NAME_ZDIFFKINGPINCASTER = "zdiffkingpincaster";

    /** Generated column name */
    public static final String COL_NAME_ZDIFFTOEFA = "zdifftoefa";

    /** Generated column name */
    public static final String COL_NAME_ZDIFFTOEFAOK = "zdifftoefaok";

    /** Generated column name */
    public static final String COL_NAME_ZDIFFTOERA = "zdifftoera";

    /** Generated column name */
    public static final String COL_NAME_ZDIFFTOERAOK = "zdifftoeraok";

    /** Generated column name */
    public static final String COL_NAME_ZESPOK = "zespok";

    /** Generated column name */
    public static final String COL_NAME_ZKINGPINCASTERFL = "zkingpincasterfl";

    /** Generated column name */
    public static final String COL_NAME_ZKINGPINCASTERFR = "zkingpincasterfr";

    /** Generated column name */
    public static final String COL_NAME_ZKINGPINCASTEROK = "zkingpincasterok";

    /** Generated column name */
    public static final String COL_NAME_ZLINENO = "zlineno";

    /** Generated column name */
    public static final String COL_NAME_ZMAXCORNERFL = "zmaxcornerfl";

    /** Generated column name */
    public static final String COL_NAME_ZMAXCORNERFR = "zmaxcornerfr";

    /** Generated column name */
    public static final String COL_NAME_ZMAXCORNEROK = "zmaxcornerok";

    /** Generated column name */
    public static final String COL_NAME_ZOVERALLOK = "zoverallok";

    /** Generated column name */
    public static final String COL_NAME_ZOVERALLRESULT = "zoverallresult";

    /** Generated column name */
    public static final String COL_NAME_ZPLANT = "zplant";

    /** Generated column name */
    public static final String COL_NAME_ZSWA = "zswa";

    /** Generated column name */
    public static final String COL_NAME_ZTOEFL = "ztoefl";

    /** Generated column name */
    public static final String COL_NAME_ZTOEFLOK = "ztoeflok";

    /** Generated column name */
    public static final String COL_NAME_ZTOEFR = "ztoefr";

    /** Generated column name */
    public static final String COL_NAME_ZTOEFROK = "ztoefrok";

    /** Generated column name */
    public static final String COL_NAME_ZTOERL = "ztoerl";

    /** Generated column name */
    public static final String COL_NAME_ZTOERLOK = "ztoerlok";

    /** Generated column name */
    public static final String COL_NAME_ZTOERR = "ztoerr";

    /** Generated column name */
    public static final String COL_NAME_ZTOERROK = "ztoerrok";

    /** Generated column name */
    public static final String COL_NAME_ZTOEUNIT = "ztoeunit";

    /** Generated column name */
    public static final String COL_NAME_ZTOTALTOEFA = "ztotaltoefa";

    /** Generated column name */
    public static final String COL_NAME_ZTOTALTOEFAOK = "ztotaltoefaok";

    /** Generated column name */
    public static final String COL_NAME_ZTOTALTOERA = "ztotaltoera";

    /** Generated column name */
    public static final String COL_NAME_ZTOTALTOERAOK = "ztotaltoeraok";

    /** Generated column name */
    public static final String COL_NAME_ZVIN = "zvin";

    /** Generated column name */
    public static final String COL_NAME_ZWEDGEANGLE = "zwedgeangle";

    /** Generated column name */
    public static final String COL_NAME_ZWEDGEANGLEOK = "zwedgeangleok";

    @Override
    public String getATDefinitionName() {
        return ATDEFINITION_NAME;
    }
    
    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESGeneratedASIMClFwalignment(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     *
     * @param source The source to copy.
     */
    public MESGeneratedASIMClFwalignment(MESGeneratedASIMClFwalignment source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESGeneratedASIMClFwalignment(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESGeneratedASIMClFwalignment() {
        super();
    }

    /**
     * Generated method definition
     *
     * @param server The Server object
     * @return the filter object
     */
    public static MESASIMClFwalignmentFilter createFilter(Server server) {
        return new MESASIMClFwalignmentFilter(server);
    }

    /**
     * Generated method definition
     *
     * @return the filter object
     */
    public static MESASIMClFwalignmentFilter createFilter() {
        return new MESASIMClFwalignmentFilter();
    }

    /**
     * Generated method definition
     *
     * @param filter the Filter object
     * @return the list of the objects
     */
    public static List<IMESASIMClFwalignment> getFilteredObjects(MESASIMClFwalignmentFilter filter) {
        return MESATObject.getFilteredMESATObjectList(filter, MESASIMClFwalignment.class);
    }

    @Override
    public boolean refresh() {
        boolean ok = super.refresh();
        if (!ok) {
            return false;
        }
        
        return true;
    }    

    @Override
    public String getZcamberfl() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZCAMBERFL);
    }

    @Override
    public void setZcamberfl(String value) {
        String oldValue = this.getZcamberfl();
        this.dgtATRow.setValue(COL_NAME_ZCAMBERFL, value);
        pcs.firePropertyChange(PROP_NAME_ZCAMBERFL, oldValue, value);
    }

    @Override
    public String getZcamberflok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZCAMBERFLOK);
    }

    @Override
    public void setZcamberflok(String value) {
        String oldValue = this.getZcamberflok();
        this.dgtATRow.setValue(COL_NAME_ZCAMBERFLOK, value);
        pcs.firePropertyChange(PROP_NAME_ZCAMBERFLOK, oldValue, value);
    }

    @Override
    public String getZcamberfr() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZCAMBERFR);
    }

    @Override
    public void setZcamberfr(String value) {
        String oldValue = this.getZcamberfr();
        this.dgtATRow.setValue(COL_NAME_ZCAMBERFR, value);
        pcs.firePropertyChange(PROP_NAME_ZCAMBERFR, oldValue, value);
    }

    @Override
    public String getZcamberfrok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZCAMBERFROK);
    }

    @Override
    public void setZcamberfrok(String value) {
        String oldValue = this.getZcamberfrok();
        this.dgtATRow.setValue(COL_NAME_ZCAMBERFROK, value);
        pcs.firePropertyChange(PROP_NAME_ZCAMBERFROK, oldValue, value);
    }

    @Override
    public String getZcamberrl() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZCAMBERRL);
    }

    @Override
    public void setZcamberrl(String value) {
        String oldValue = this.getZcamberrl();
        this.dgtATRow.setValue(COL_NAME_ZCAMBERRL, value);
        pcs.firePropertyChange(PROP_NAME_ZCAMBERRL, oldValue, value);
    }

    @Override
    public String getZcamberrlok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZCAMBERRLOK);
    }

    @Override
    public void setZcamberrlok(String value) {
        String oldValue = this.getZcamberrlok();
        this.dgtATRow.setValue(COL_NAME_ZCAMBERRLOK, value);
        pcs.firePropertyChange(PROP_NAME_ZCAMBERRLOK, oldValue, value);
    }

    @Override
    public String getZcamberrr() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZCAMBERRR);
    }

    @Override
    public void setZcamberrr(String value) {
        String oldValue = this.getZcamberrr();
        this.dgtATRow.setValue(COL_NAME_ZCAMBERRR, value);
        pcs.firePropertyChange(PROP_NAME_ZCAMBERRR, oldValue, value);
    }

    @Override
    public String getZcamberrrok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZCAMBERRROK);
    }

    @Override
    public void setZcamberrrok(String value) {
        String oldValue = this.getZcamberrrok();
        this.dgtATRow.setValue(COL_NAME_ZCAMBERRROK, value);
        pcs.firePropertyChange(PROP_NAME_ZCAMBERRROK, oldValue, value);
    }

    @Override
    public String getZcamberunit() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZCAMBERUNIT);
    }

    @Override
    public void setZcamberunit(String value) {
        String oldValue = this.getZcamberunit();
        this.dgtATRow.setValue(COL_NAME_ZCAMBERUNIT, value);
        pcs.firePropertyChange(PROP_NAME_ZCAMBERUNIT, oldValue, value);
    }

    @Override
    public String getZdiffcamberfa() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZDIFFCAMBERFA);
    }

    @Override
    public void setZdiffcamberfa(String value) {
        String oldValue = this.getZdiffcamberfa();
        this.dgtATRow.setValue(COL_NAME_ZDIFFCAMBERFA, value);
        pcs.firePropertyChange(PROP_NAME_ZDIFFCAMBERFA, oldValue, value);
    }

    @Override
    public String getZdiffcamberfaok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZDIFFCAMBERFAOK);
    }

    @Override
    public void setZdiffcamberfaok(String value) {
        String oldValue = this.getZdiffcamberfaok();
        this.dgtATRow.setValue(COL_NAME_ZDIFFCAMBERFAOK, value);
        pcs.firePropertyChange(PROP_NAME_ZDIFFCAMBERFAOK, oldValue, value);
    }

    @Override
    public String getZdiffcamberra() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZDIFFCAMBERRA);
    }

    @Override
    public void setZdiffcamberra(String value) {
        String oldValue = this.getZdiffcamberra();
        this.dgtATRow.setValue(COL_NAME_ZDIFFCAMBERRA, value);
        pcs.firePropertyChange(PROP_NAME_ZDIFFCAMBERRA, oldValue, value);
    }

    @Override
    public String getZdiffcamberraok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZDIFFCAMBERRAOK);
    }

    @Override
    public void setZdiffcamberraok(String value) {
        String oldValue = this.getZdiffcamberraok();
        this.dgtATRow.setValue(COL_NAME_ZDIFFCAMBERRAOK, value);
        pcs.firePropertyChange(PROP_NAME_ZDIFFCAMBERRAOK, oldValue, value);
    }

    @Override
    public String getZdiffkingpincaster() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZDIFFKINGPINCASTER);
    }

    @Override
    public void setZdiffkingpincaster(String value) {
        String oldValue = this.getZdiffkingpincaster();
        this.dgtATRow.setValue(COL_NAME_ZDIFFKINGPINCASTER, value);
        pcs.firePropertyChange(PROP_NAME_ZDIFFKINGPINCASTER, oldValue, value);
    }

    @Override
    public String getZdifftoefa() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZDIFFTOEFA);
    }

    @Override
    public void setZdifftoefa(String value) {
        String oldValue = this.getZdifftoefa();
        this.dgtATRow.setValue(COL_NAME_ZDIFFTOEFA, value);
        pcs.firePropertyChange(PROP_NAME_ZDIFFTOEFA, oldValue, value);
    }

    @Override
    public String getZdifftoefaok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZDIFFTOEFAOK);
    }

    @Override
    public void setZdifftoefaok(String value) {
        String oldValue = this.getZdifftoefaok();
        this.dgtATRow.setValue(COL_NAME_ZDIFFTOEFAOK, value);
        pcs.firePropertyChange(PROP_NAME_ZDIFFTOEFAOK, oldValue, value);
    }

    @Override
    public String getZdifftoera() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZDIFFTOERA);
    }

    @Override
    public void setZdifftoera(String value) {
        String oldValue = this.getZdifftoera();
        this.dgtATRow.setValue(COL_NAME_ZDIFFTOERA, value);
        pcs.firePropertyChange(PROP_NAME_ZDIFFTOERA, oldValue, value);
    }

    @Override
    public String getZdifftoeraok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZDIFFTOERAOK);
    }

    @Override
    public void setZdifftoeraok(String value) {
        String oldValue = this.getZdifftoeraok();
        this.dgtATRow.setValue(COL_NAME_ZDIFFTOERAOK, value);
        pcs.firePropertyChange(PROP_NAME_ZDIFFTOERAOK, oldValue, value);
    }

    @Override
    public String getZespok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZESPOK);
    }

    @Override
    public void setZespok(String value) {
        String oldValue = this.getZespok();
        this.dgtATRow.setValue(COL_NAME_ZESPOK, value);
        pcs.firePropertyChange(PROP_NAME_ZESPOK, oldValue, value);
    }

    @Override
    public String getZkingpincasterfl() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZKINGPINCASTERFL);
    }

    @Override
    public void setZkingpincasterfl(String value) {
        String oldValue = this.getZkingpincasterfl();
        this.dgtATRow.setValue(COL_NAME_ZKINGPINCASTERFL, value);
        pcs.firePropertyChange(PROP_NAME_ZKINGPINCASTERFL, oldValue, value);
    }

    @Override
    public String getZkingpincasterfr() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZKINGPINCASTERFR);
    }

    @Override
    public void setZkingpincasterfr(String value) {
        String oldValue = this.getZkingpincasterfr();
        this.dgtATRow.setValue(COL_NAME_ZKINGPINCASTERFR, value);
        pcs.firePropertyChange(PROP_NAME_ZKINGPINCASTERFR, oldValue, value);
    }

    @Override
    public String getZkingpincasterok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZKINGPINCASTEROK);
    }

    @Override
    public void setZkingpincasterok(String value) {
        String oldValue = this.getZkingpincasterok();
        this.dgtATRow.setValue(COL_NAME_ZKINGPINCASTEROK, value);
        pcs.firePropertyChange(PROP_NAME_ZKINGPINCASTEROK, oldValue, value);
    }

    @Override
    public String getZlineno() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZLINENO);
    }

    @Override
    public void setZlineno(String value) {
        String oldValue = this.getZlineno();
        this.dgtATRow.setValue(COL_NAME_ZLINENO, value);
        pcs.firePropertyChange(PROP_NAME_ZLINENO, oldValue, value);
    }

    @Override
    public String getZmaxcornerfl() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZMAXCORNERFL);
    }

    @Override
    public void setZmaxcornerfl(String value) {
        String oldValue = this.getZmaxcornerfl();
        this.dgtATRow.setValue(COL_NAME_ZMAXCORNERFL, value);
        pcs.firePropertyChange(PROP_NAME_ZMAXCORNERFL, oldValue, value);
    }

    @Override
    public String getZmaxcornerfr() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZMAXCORNERFR);
    }

    @Override
    public void setZmaxcornerfr(String value) {
        String oldValue = this.getZmaxcornerfr();
        this.dgtATRow.setValue(COL_NAME_ZMAXCORNERFR, value);
        pcs.firePropertyChange(PROP_NAME_ZMAXCORNERFR, oldValue, value);
    }

    @Override
    public String getZmaxcornerok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZMAXCORNEROK);
    }

    @Override
    public void setZmaxcornerok(String value) {
        String oldValue = this.getZmaxcornerok();
        this.dgtATRow.setValue(COL_NAME_ZMAXCORNEROK, value);
        pcs.firePropertyChange(PROP_NAME_ZMAXCORNEROK, oldValue, value);
    }

    @Override
    public String getZoverallok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZOVERALLOK);
    }

    @Override
    public void setZoverallok(String value) {
        String oldValue = this.getZoverallok();
        this.dgtATRow.setValue(COL_NAME_ZOVERALLOK, value);
        pcs.firePropertyChange(PROP_NAME_ZOVERALLOK, oldValue, value);
    }

    @Override
    public String getZoverallresult() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZOVERALLRESULT);
    }

    @Override
    public void setZoverallresult(String value) {
        String oldValue = this.getZoverallresult();
        this.dgtATRow.setValue(COL_NAME_ZOVERALLRESULT, value);
        pcs.firePropertyChange(PROP_NAME_ZOVERALLRESULT, oldValue, value);
    }

    @Override
    public String getZplant() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZPLANT);
    }

    @Override
    public void setZplant(String value) {
        String oldValue = this.getZplant();
        this.dgtATRow.setValue(COL_NAME_ZPLANT, value);
        pcs.firePropertyChange(PROP_NAME_ZPLANT, oldValue, value);
    }

    @Override
    public String getZswa() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZSWA);
    }

    @Override
    public void setZswa(String value) {
        String oldValue = this.getZswa();
        this.dgtATRow.setValue(COL_NAME_ZSWA, value);
        pcs.firePropertyChange(PROP_NAME_ZSWA, oldValue, value);
    }

    @Override
    public String getZtoefl() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZTOEFL);
    }

    @Override
    public void setZtoefl(String value) {
        String oldValue = this.getZtoefl();
        this.dgtATRow.setValue(COL_NAME_ZTOEFL, value);
        pcs.firePropertyChange(PROP_NAME_ZTOEFL, oldValue, value);
    }

    @Override
    public String getZtoeflok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZTOEFLOK);
    }

    @Override
    public void setZtoeflok(String value) {
        String oldValue = this.getZtoeflok();
        this.dgtATRow.setValue(COL_NAME_ZTOEFLOK, value);
        pcs.firePropertyChange(PROP_NAME_ZTOEFLOK, oldValue, value);
    }

    @Override
    public String getZtoefr() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZTOEFR);
    }

    @Override
    public void setZtoefr(String value) {
        String oldValue = this.getZtoefr();
        this.dgtATRow.setValue(COL_NAME_ZTOEFR, value);
        pcs.firePropertyChange(PROP_NAME_ZTOEFR, oldValue, value);
    }

    @Override
    public String getZtoefrok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZTOEFROK);
    }

    @Override
    public void setZtoefrok(String value) {
        String oldValue = this.getZtoefrok();
        this.dgtATRow.setValue(COL_NAME_ZTOEFROK, value);
        pcs.firePropertyChange(PROP_NAME_ZTOEFROK, oldValue, value);
    }

    @Override
    public String getZtoerl() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZTOERL);
    }

    @Override
    public void setZtoerl(String value) {
        String oldValue = this.getZtoerl();
        this.dgtATRow.setValue(COL_NAME_ZTOERL, value);
        pcs.firePropertyChange(PROP_NAME_ZTOERL, oldValue, value);
    }

    @Override
    public String getZtoerlok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZTOERLOK);
    }

    @Override
    public void setZtoerlok(String value) {
        String oldValue = this.getZtoerlok();
        this.dgtATRow.setValue(COL_NAME_ZTOERLOK, value);
        pcs.firePropertyChange(PROP_NAME_ZTOERLOK, oldValue, value);
    }

    @Override
    public String getZtoerr() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZTOERR);
    }

    @Override
    public void setZtoerr(String value) {
        String oldValue = this.getZtoerr();
        this.dgtATRow.setValue(COL_NAME_ZTOERR, value);
        pcs.firePropertyChange(PROP_NAME_ZTOERR, oldValue, value);
    }

    @Override
    public String getZtoerrok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZTOERROK);
    }

    @Override
    public void setZtoerrok(String value) {
        String oldValue = this.getZtoerrok();
        this.dgtATRow.setValue(COL_NAME_ZTOERROK, value);
        pcs.firePropertyChange(PROP_NAME_ZTOERROK, oldValue, value);
    }

    @Override
    public String getZtoeunit() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZTOEUNIT);
    }

    @Override
    public void setZtoeunit(String value) {
        String oldValue = this.getZtoeunit();
        this.dgtATRow.setValue(COL_NAME_ZTOEUNIT, value);
        pcs.firePropertyChange(PROP_NAME_ZTOEUNIT, oldValue, value);
    }

    @Override
    public String getZtotaltoefa() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZTOTALTOEFA);
    }

    @Override
    public void setZtotaltoefa(String value) {
        String oldValue = this.getZtotaltoefa();
        this.dgtATRow.setValue(COL_NAME_ZTOTALTOEFA, value);
        pcs.firePropertyChange(PROP_NAME_ZTOTALTOEFA, oldValue, value);
    }

    @Override
    public String getZtotaltoefaok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZTOTALTOEFAOK);
    }

    @Override
    public void setZtotaltoefaok(String value) {
        String oldValue = this.getZtotaltoefaok();
        this.dgtATRow.setValue(COL_NAME_ZTOTALTOEFAOK, value);
        pcs.firePropertyChange(PROP_NAME_ZTOTALTOEFAOK, oldValue, value);
    }

    @Override
    public String getZtotaltoera() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZTOTALTOERA);
    }

    @Override
    public void setZtotaltoera(String value) {
        String oldValue = this.getZtotaltoera();
        this.dgtATRow.setValue(COL_NAME_ZTOTALTOERA, value);
        pcs.firePropertyChange(PROP_NAME_ZTOTALTOERA, oldValue, value);
    }

    @Override
    public String getZtotaltoeraok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZTOTALTOERAOK);
    }

    @Override
    public void setZtotaltoeraok(String value) {
        String oldValue = this.getZtotaltoeraok();
        this.dgtATRow.setValue(COL_NAME_ZTOTALTOERAOK, value);
        pcs.firePropertyChange(PROP_NAME_ZTOTALTOERAOK, oldValue, value);
    }

    @Override
    public String getZvin() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZVIN);
    }

    @Override
    public void setZvin(String value) {
        String oldValue = this.getZvin();
        this.dgtATRow.setValue(COL_NAME_ZVIN, value);
        pcs.firePropertyChange(PROP_NAME_ZVIN, oldValue, value);
    }

    @Override
    public String getZwedgeangle() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZWEDGEANGLE);
    }

    @Override
    public void setZwedgeangle(String value) {
        String oldValue = this.getZwedgeangle();
        this.dgtATRow.setValue(COL_NAME_ZWEDGEANGLE, value);
        pcs.firePropertyChange(PROP_NAME_ZWEDGEANGLE, oldValue, value);
    }

    @Override
    public String getZwedgeangleok() {
        return (String) this.dgtATRow.getValue(COL_NAME_ZWEDGEANGLEOK);
    }

    @Override
    public void setZwedgeangleok(String value) {
        String oldValue = this.getZwedgeangleok();
        this.dgtATRow.setValue(COL_NAME_ZWEDGEANGLEOK, value);
        pcs.firePropertyChange(PROP_NAME_ZWEDGEANGLEOK, oldValue, value);
    }

    // CHECKSTYLE:MethodNameCheck:off
    @Override
    public void Save(Time time, String comment, AccessPrivilege accessPrivilege) throws DatasweepException {
        // Check if attached reference is valid:
        Response res = new Response();
        if (res.isError()) {
            throw new DatasweepException(res);
        }
        // okay, save here.
        super.Save(time, comment, accessPrivilege);
    }
     // CHECKSTYLE:MethodNameCheck:on
     
}
