// CHECKSTYLE:FileLength:off (reason:generated)
// CHECKSTYLE:LineLength:off (reason:generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESATObject;

import com.datasweep.compatibility.ui.Time;

/**
 * Generated interface definition for application table AS_IM_Vcats_EcukPsn.
 * Application table description: null
 * @ftps.exclude 
 */
public interface IMESGeneratedASIMVcatsEcukPsn extends IMESATObject {

    /** Generated attribute definition */
    public static final String ATDEFINITION_NAME = "AS_IM_Vcats_EcukPsn";


    /** Generated property name */
    public static final String PROP_NAME_SENDSTATUS = "sendstatus";

    /** Generated column name */
    public static final String SQL_COL_NAME_SENDSTATUS = "send_status_I";
    

    /** Generated property name */
    public static final String PROP_NAME_SENDTIME = "sendtime";

    /** Generated column name */
    public static final String SQL_COL_NAME_SENDTIME = "send_time_T";
    

    /** Generated property name */
    public static final String PROP_NAME_VIN = "vin";

    /** Generated column name */
    public static final String SQL_COL_NAME_VIN = "vin_S";
    
    /**
     * Generated getter for column send_status.
     * Column description: 
     *
     * @return the requested value
     */
    public Long getSendstatus();

    /**
     * Generated setter for column send_status.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setSendstatus(Long value);

    /**
     * Generated getter for column send_time.
     * Column description: 
     *
     * @return the requested value
     */
    public Time getSendtime();

    /**
     * Generated setter for column send_time.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setSendtime(Time value);

    /**
     * Generated getter for column vin.
     * Column description: 
     *
     * @return the requested value
     */
    public String getVin();

    /**
     * Generated setter for column vin.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setVin(String value);

}
