// CHECKSTYLE:FileLength:off (reason: generated)
// CHECKSTYLE:LineLength:off (reason: generated)
// CHECKSTYLE:MethodLength:off (reason: generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file is generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
 
import java.util.List;
 
import com.datasweep.compatibility.client.ATRow; 
import com.datasweep.compatibility.client.AccessPrivilege;
import com.datasweep.compatibility.client.DatasweepException;
import com.datasweep.compatibility.client.Response;
import com.datasweep.compatibility.client.Server;
import com.datasweep.compatibility.ui.Time;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;

import ... tbd ... // TODO Please specify package name.IMESASIMVcatsEcukPsn;
import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMVcatsEcukPsn;
import ... tbd ... // TODO Please specify package name.MESASIMVcatsEcukPsn;
import ... tbd ... // TODO Please specify package name.MESASIMVcatsEcukPsnFilter;


/**
 * Generated class definition for application table AS_IM_Vcats_EcukPsn.
 * Application table description: null
 */
public class MESGeneratedASIMVcatsEcukPsn extends MESATObject //nl
                                                 implements IMESGeneratedASIMVcatsEcukPsn {


    /** Generated column name */
    public static final String COL_NAME_SENDSTATUS = "send_status";

    /** Generated column name */
    public static final String COL_NAME_SENDTIME = "send_time";

    /** Generated column name */
    public static final String COL_NAME_VIN = "vin";

    @Override
    public String getATDefinitionName() {
        return ATDEFINITION_NAME;
    }
    
    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESGeneratedASIMVcatsEcukPsn(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     *
     * @param source The source to copy.
     */
    public MESGeneratedASIMVcatsEcukPsn(MESGeneratedASIMVcatsEcukPsn source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESGeneratedASIMVcatsEcukPsn(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESGeneratedASIMVcatsEcukPsn() {
        super();
    }

    /**
     * Generated method definition
     *
     * @param server The Server object
     * @return the filter object
     */
    public static MESASIMVcatsEcukPsnFilter createFilter(Server server) {
        return new MESASIMVcatsEcukPsnFilter(server);
    }

    /**
     * Generated method definition
     *
     * @return the filter object
     */
    public static MESASIMVcatsEcukPsnFilter createFilter() {
        return new MESASIMVcatsEcukPsnFilter();
    }

    /**
     * Generated method definition
     *
     * @param filter the Filter object
     * @return the list of the objects
     */
    public static List<IMESASIMVcatsEcukPsn> getFilteredObjects(MESASIMVcatsEcukPsnFilter filter) {
        return MESATObject.getFilteredMESATObjectList(filter, MESASIMVcatsEcukPsn.class);
    }

    @Override
    public boolean refresh() {
        boolean ok = super.refresh();
        if (!ok) {
            return false;
        }
        
        return true;
    }    

    @Override
    public Long getSendstatus() {
        return (Long) this.dgtATRow.getValue(COL_NAME_SENDSTATUS);
    }

    @Override
    public void setSendstatus(Long value) {
        Long oldValue = this.getSendstatus();
        this.dgtATRow.setValue(COL_NAME_SENDSTATUS, value);
        pcs.firePropertyChange(PROP_NAME_SENDSTATUS, oldValue, value);
    }

    @Override
    public Time getSendtime() {
        return (Time) this.dgtATRow.getValue(COL_NAME_SENDTIME);
    }

    @Override
    public void setSendtime(Time value) {
        Time oldValue = this.getSendtime();
        this.dgtATRow.setValue(COL_NAME_SENDTIME, value);
        pcs.firePropertyChange(PROP_NAME_SENDTIME, oldValue, value);
    }

    @Override
    public String getVin() {
        return (String) this.dgtATRow.getValue(COL_NAME_VIN);
    }

    @Override
    public void setVin(String value) {
        String oldValue = this.getVin();
        this.dgtATRow.setValue(COL_NAME_VIN, value);
        pcs.firePropertyChange(PROP_NAME_VIN, oldValue, value);
    }

    // CHECKSTYLE:MethodNameCheck:off
    @Override
    public void Save(Time time, String comment, AccessPrivilege accessPrivilege) throws DatasweepException {
        // Check if attached reference is valid:
        Response res = new Response();
        if (res.isError()) {
            throw new DatasweepException(res);
        }
        // okay, save here.
        super.Save(time, comment, accessPrivilege);
    }
     // CHECKSTYLE:MethodNameCheck:on
     
}
