package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMHeadlightDetectionFilter;

/**
 * Generated filter interface for application table AS_IM_Headlight_Detection.
 * @ftps.exclude 
 */
public interface IMESASIMHeadlightDetectionFilter extends IMESGeneratedASIMHeadlightDetectionFilter {
}
