package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.ATRow;

import ... tbd ... // TODO Please specify package name.IMESASIMHeadlightDetection;
import ... tbd ... // TODO Please specify package name.MESGeneratedASIMHeadlightDetection;

/**
 * Generated class definition for application table AS_IM_Headlight_Detection.
 * Application table description: null
 */
public class MESASIMHeadlightDetection extends MESGeneratedASIMHeadlightDetection //nl
                                        implements IMESASIMHeadlightDetection {

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESASIMHeadlightDetection(long key) {
        super(key);
    }

    /**
     * Generated constructor
     *
     * @param source the source to copy.
     */
    public MESASIMHeadlightDetection(MESASIMHeadlightDetection source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESASIMHeadlightDetection(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESASIMHeadlightDetection() {
        super();
    }

}
