package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.ATRow;

import ... tbd ... // TODO Please specify package name.IMESASIMAvmDetection;
import ... tbd ... // TODO Please specify package name.MESGeneratedASIMAvmDetection;

/**
 * Generated class definition for application table AS_IM_AvmDetection.
 * Application table description: null
 */
public class MESASIMAvmDetection extends MESGeneratedASIMAvmDetection //nl
                                        implements IMESASIMAvmDetection {

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESASIMAvmDetection(long key) {
        super(key);
    }

    /**
     * Generated constructor
     *
     * @param source the source to copy.
     */
    public MESASIMAvmDetection(MESASIMAvmDetection source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESASIMAvmDetection(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESASIMAvmDetection() {
        super();
    }

}
