// CHECKSTYLE:FileLength:off (reason: generated)
// CHECKSTYLE:LineLength:off (reason: generated)
// CHECKSTYLE:MethodLength:off (reason: generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import java.util.List;

import com.datasweep.compatibility.client.ATRowFilter;
import com.datasweep.compatibility.client.DatasweepException;
import com.datasweep.compatibility.client.Server;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;
import com.rockwell.mes.commons.base.ifc.services.PCContext;

import ... tbd ... // TODO Please specify package name.IMESASIMAvmDetection;
import ... tbd ... // TODO Please specify package name.IMESASIMAvmDetectionFilter;
import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMAvmDetectionFilter;
import ... tbd ... // TODO Please specify package name.MESASIMAvmDetection;


/**
 * Generated filter class for application table AS_IM_AvmDetection.
 */
public class MESGeneratedASIMAvmDetectionFilter extends ATRowFilter implements IMESGeneratedASIMAvmDetectionFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /** Generated attribute definition */
    protected static final String ATDEFINITION_NAME = "AS_IM_AvmDetection";

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESGeneratedASIMAvmDetectionFilter(Server server) {
        super(server, ATDEFINITION_NAME);
    }

    /**
     * Generated default constructor
     */
    public MESGeneratedASIMAvmDetectionFilter() {
        this(PCContext.getServerImpl());
    }

    @Override
    public List<IMESASIMAvmDetection> getFilteredObjects() {
        return MESATObject.getFilteredMESATObjectList(this, MESASIMAvmDetection.class);
    }

    @Override
    public IMESASIMAvmDetectionFilter forAvmContaining(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameContaining(MESGeneratedASIMAvmDetection.COL_NAME_AVM, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forAvmEqualTo(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameEqualTo(MESGeneratedASIMAvmDetection.COL_NAME_AVM, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forAvmNotEqualTo(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameNotEqualTo(MESGeneratedASIMAvmDetection.COL_NAME_AVM, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forAvmStartingWith(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameStartingWith(MESGeneratedASIMAvmDetection.COL_NAME_AVM, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forZlinenoContaining(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameContaining(MESGeneratedASIMAvmDetection.COL_NAME_ZLINENO, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forZlinenoEqualTo(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameEqualTo(MESGeneratedASIMAvmDetection.COL_NAME_ZLINENO, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forZlinenoNotEqualTo(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameNotEqualTo(MESGeneratedASIMAvmDetection.COL_NAME_ZLINENO, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forZlinenoStartingWith(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameStartingWith(MESGeneratedASIMAvmDetection.COL_NAME_ZLINENO, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forZoverallresultContaining(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameContaining(MESGeneratedASIMAvmDetection.COL_NAME_ZOVERALLRESULT, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forZoverallresultEqualTo(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameEqualTo(MESGeneratedASIMAvmDetection.COL_NAME_ZOVERALLRESULT, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forZoverallresultNotEqualTo(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameNotEqualTo(MESGeneratedASIMAvmDetection.COL_NAME_ZOVERALLRESULT, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forZoverallresultStartingWith(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameStartingWith(MESGeneratedASIMAvmDetection.COL_NAME_ZOVERALLRESULT, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forZplantContaining(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameContaining(MESGeneratedASIMAvmDetection.COL_NAME_ZPLANT, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forZplantEqualTo(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameEqualTo(MESGeneratedASIMAvmDetection.COL_NAME_ZPLANT, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forZplantNotEqualTo(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameNotEqualTo(MESGeneratedASIMAvmDetection.COL_NAME_ZPLANT, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forZplantStartingWith(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameStartingWith(MESGeneratedASIMAvmDetection.COL_NAME_ZPLANT, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forZvinContaining(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameContaining(MESGeneratedASIMAvmDetection.COL_NAME_ZVIN, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forZvinEqualTo(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameEqualTo(MESGeneratedASIMAvmDetection.COL_NAME_ZVIN, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forZvinNotEqualTo(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameNotEqualTo(MESGeneratedASIMAvmDetection.COL_NAME_ZVIN, value);
    }
    @Override
    public IMESASIMAvmDetectionFilter forZvinStartingWith(String value) throws DatasweepException {
        return (IMESASIMAvmDetectionFilter) forColumnNameStartingWith(MESGeneratedASIMAvmDetection.COL_NAME_ZVIN, value);
    }
}
