package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.Server;

import ... tbd ... // TODO Please specify package name.IMESASIMVCATSProcessResultFilter;
import ... tbd ... // TODO Please specify package name.MESGeneratedASIMVCATSProcessResultFilter;

/**
 * Generated filter class for application table AS_IM_VCATS_ProcessResult.
 */
public class MESASIMVCATSProcessResultFilter extends MESGeneratedASIMVCATSProcessResultFilter //nl
                                              implements IMESASIMVCATSProcessResultFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESASIMVCATSProcessResultFilter(Server server) {
        super(server);
    }

    /**
     * Generated default constructor
     */
    public MESASIMVCATSProcessResultFilter() {
        super();
    }
}
