package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.ATRow;

import ... tbd ... // TODO Please specify package name.IMESASIMVCATSECUPartNo;
import ... tbd ... // TODO Please specify package name.MESGeneratedASIMVCATSECUPartNo;

/**
 * Generated class definition for application table AS_IM_VCATS_ECUPartNo.
 * Application table description: null
 */
public class MESASIMVCATSECUPartNo extends MESGeneratedASIMVCATSECUPartNo //nl
                                        implements IMESASIMVCATSECUPartNo {

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESASIMVCATSECUPartNo(long key) {
        super(key);
    }

    /**
     * Generated constructor
     *
     * @param source the source to copy.
     */
    public MESASIMVCATSECUPartNo(MESASIMVCATSECUPartNo source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESASIMVCATSECUPartNo(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESASIMVCATSECUPartNo() {
        super();
    }

}
