package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.Server;

import ... tbd ... // TODO Please specify package name.IMESASIMVCATSECUPartNoFilter;
import ... tbd ... // TODO Please specify package name.MESGeneratedASIMVCATSECUPartNoFilter;

/**
 * Generated filter class for application table AS_IM_VCATS_ECUPartNo.
 */
public class MESASIMVCATSECUPartNoFilter extends MESGeneratedASIMVCATSECUPartNoFilter //nl
                                              implements IMESASIMVCATSECUPartNoFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESASIMVCATSECUPartNoFilter(Server server) {
        super(server);
    }

    /**
     * Generated default constructor
     */
    public MESASIMVCATSECUPartNoFilter() {
        super();
    }
}
