// CHECKSTYLE:FileLength:off (reason: generated)
// CHECKSTYLE:LineLength:off (reason: generated)
// CHECKSTYLE:MethodLength:off (reason: generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import java.util.List;

import com.datasweep.compatibility.client.ATRowFilter;
import com.datasweep.compatibility.client.DatasweepException;
import com.datasweep.compatibility.client.Server;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;
import com.rockwell.mes.commons.base.ifc.services.PCContext;

import ... tbd ... // TODO Please specify package name.IMESASIMVCATSECUPartNo;
import ... tbd ... // TODO Please specify package name.IMESASIMVCATSECUPartNoFilter;
import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMVCATSECUPartNoFilter;
import ... tbd ... // TODO Please specify package name.MESASIMVCATSECUPartNo;


/**
 * Generated filter class for application table AS_IM_VCATS_ECUPartNo.
 */
public class MESGeneratedASIMVCATSECUPartNoFilter extends ATRowFilter implements IMESGeneratedASIMVCATSECUPartNoFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /** Generated attribute definition */
    protected static final String ATDEFINITION_NAME = "AS_IM_VCATS_ECUPartNo";

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESGeneratedASIMVCATSECUPartNoFilter(Server server) {
        super(server, ATDEFINITION_NAME);
    }

    /**
     * Generated default constructor
     */
    public MESGeneratedASIMVCATSECUPartNoFilter() {
        this(PCContext.getServerImpl());
    }

    @Override
    public List<IMESASIMVCATSECUPartNo> getFilteredObjects() {
        return MESATObject.getFilteredMESATObjectList(this, MESASIMVCATSECUPartNo.class);
    }

    @Override
    public IMESASIMVCATSECUPartNoFilter forEcupartContaining(String value) throws DatasweepException {
        return (IMESASIMVCATSECUPartNoFilter) forColumnNameContaining(MESGeneratedASIMVCATSECUPartNo.COL_NAME_ECUPART, value);
    }
    @Override
    public IMESASIMVCATSECUPartNoFilter forEcupartEqualTo(String value) throws DatasweepException {
        return (IMESASIMVCATSECUPartNoFilter) forColumnNameEqualTo(MESGeneratedASIMVCATSECUPartNo.COL_NAME_ECUPART, value);
    }
    @Override
    public IMESASIMVCATSECUPartNoFilter forEcupartNotEqualTo(String value) throws DatasweepException {
        return (IMESASIMVCATSECUPartNoFilter) forColumnNameNotEqualTo(MESGeneratedASIMVCATSECUPartNo.COL_NAME_ECUPART, value);
    }
    @Override
    public IMESASIMVCATSECUPartNoFilter forEcupartStartingWith(String value) throws DatasweepException {
        return (IMESASIMVCATSECUPartNoFilter) forColumnNameStartingWith(MESGeneratedASIMVCATSECUPartNo.COL_NAME_ECUPART, value);
    }
    @Override
    public IMESASIMVCATSECUPartNoFilter forVinContaining(String value) throws DatasweepException {
        return (IMESASIMVCATSECUPartNoFilter) forColumnNameContaining(MESGeneratedASIMVCATSECUPartNo.COL_NAME_VIN, value);
    }
    @Override
    public IMESASIMVCATSECUPartNoFilter forVinEqualTo(String value) throws DatasweepException {
        return (IMESASIMVCATSECUPartNoFilter) forColumnNameEqualTo(MESGeneratedASIMVCATSECUPartNo.COL_NAME_VIN, value);
    }
    @Override
    public IMESASIMVCATSECUPartNoFilter forVinNotEqualTo(String value) throws DatasweepException {
        return (IMESASIMVCATSECUPartNoFilter) forColumnNameNotEqualTo(MESGeneratedASIMVCATSECUPartNo.COL_NAME_VIN, value);
    }
    @Override
    public IMESASIMVCATSECUPartNoFilter forVinStartingWith(String value) throws DatasweepException {
        return (IMESASIMVCATSECUPartNoFilter) forColumnNameStartingWith(MESGeneratedASIMVCATSECUPartNo.COL_NAME_VIN, value);
    }
}
