package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.Server;

import ... tbd ... // TODO Please specify package name.IMESASOMElectroOrderFilter;
import ... tbd ... // TODO Please specify package name.MESGeneratedASOMElectroOrderFilter;

/**
 * Generated filter class for application table AS_OM_ElectroOrder.
 */
public class MESASOMElectroOrderFilter extends MESGeneratedASOMElectroOrderFilter //nl
                                              implements IMESASOMElectroOrderFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESASOMElectroOrderFilter(Server server) {
        super(server);
    }

    /**
     * Generated default constructor
     */
    public MESASOMElectroOrderFilter() {
        super();
    }
}
