package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESObject;

import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMVcatsEcukPsnItem;

/**
 * Generated interface definition for application table AS_IM_Vcats_EcukPsnItem.
 * Application table description: null<br>
 * @ftps.exclude 
 */
public interface IMESASIMVcatsEcukPsnItem extends IMESGeneratedASIMVcatsEcukPsnItem, IMESObject {
}
