package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.ATRow;

import ... tbd ... // TODO Please specify package name.IMESASIMVcatsEcukPsnItem;
import ... tbd ... // TODO Please specify package name.MESGeneratedASIMVcatsEcukPsnItem;

/**
 * Generated class definition for application table AS_IM_Vcats_EcukPsnItem.
 * Application table description: null
 */
public class MESASIMVcatsEcukPsnItem extends MESGeneratedASIMVcatsEcukPsnItem //nl
                                        implements IMESASIMVcatsEcukPsnItem {

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESASIMVcatsEcukPsnItem(long key) {
        super(key);
    }

    /**
     * Generated constructor
     *
     * @param source the source to copy.
     */
    public MESASIMVcatsEcukPsnItem(MESASIMVcatsEcukPsnItem source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESASIMVcatsEcukPsnItem(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESASIMVcatsEcukPsnItem() {
        super();
    }

}
