// CHECKSTYLE:FileLength:off (reason:generated)
// CHECKSTYLE:LineLength:off (reason:generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESATObject;

import com.datasweep.compatibility.ui.Time;

/**
 * Generated interface definition for application table AS_IM_ExactlyBinding.
 * Application table description: null
 * @ftps.exclude 
 */
public interface IMESGeneratedASIMExactlyBinding extends IMESATObject {

    /** Generated attribute definition */
    public static final String ATDEFINITION_NAME = "AS_IM_ExactlyBinding";


    /** Generated property name */
    public static final String PROP_NAME_BARCODE = "barcode";

    /** Generated column name */
    public static final String SQL_COL_NAME_BARCODE = "barcode_S";
    

    /** Generated property name */
    public static final String PROP_NAME_COLUMN2 = "column2";

    /** Generated column name */
    public static final String SQL_COL_NAME_COLUMN2 = "Column_2_S";
    

    /** Generated property name */
    public static final String PROP_NAME_OPERATIONCODE = "operationcode";

    /** Generated column name */
    public static final String SQL_COL_NAME_OPERATIONCODE = "operation_code_S";
    

    /** Generated property name */
    public static final String PROP_NAME_OPERATIONNAME = "operationname";

    /** Generated column name */
    public static final String SQL_COL_NAME_OPERATIONNAME = "operation_name_S";
    

    /** Generated property name */
    public static final String PROP_NAME_PARTNUMBER = "partnumber";

    /** Generated column name */
    public static final String SQL_COL_NAME_PARTNUMBER = "part_number_S";
    

    /** Generated property name */
    public static final String PROP_NAME_SCANTIME = "scantime";

    /** Generated column name */
    public static final String SQL_COL_NAME_SCANTIME = "scan_time_T";
    

    /** Generated property name */
    public static final String PROP_NAME_SENDSTATUS = "sendstatus";

    /** Generated column name */
    public static final String SQL_COL_NAME_SENDSTATUS = "send_status_S";
    

    /** Generated property name */
    public static final String PROP_NAME_SENDTIME = "sendtime";

    /** Generated column name */
    public static final String SQL_COL_NAME_SENDTIME = "send_time_T";
    

    /** Generated property name */
    public static final String PROP_NAME_STATION = "station";

    /** Generated column name */
    public static final String SQL_COL_NAME_STATION = "station_S";
    

    /** Generated property name */
    public static final String PROP_NAME_STEPCODE = "stepcode";

    /** Generated column name */
    public static final String SQL_COL_NAME_STEPCODE = "step_code_S";
    

    /** Generated property name */
    public static final String PROP_NAME_STEPNAME = "stepname";

    /** Generated column name */
    public static final String SQL_COL_NAME_STEPNAME = "step_name_S";
    

    /** Generated property name */
    public static final String PROP_NAME_USERNAME = "username";

    /** Generated column name */
    public static final String SQL_COL_NAME_USERNAME = "user_name_S";
    

    /** Generated property name */
    public static final String PROP_NAME_VIN = "vin";

    /** Generated column name */
    public static final String SQL_COL_NAME_VIN = "vin_S";
    
    /**
     * Generated getter for column barcode.
     * Column description: 
     *
     * @return the requested value
     */
    public String getBarcode();

    /**
     * Generated setter for column barcode.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setBarcode(String value);

    /**
     * Generated getter for column Column_2.
     * Column description: 
     *
     * @return the requested value
     */
    public String getColumn2();

    /**
     * Generated setter for column Column_2.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setColumn2(String value);

    /**
     * Generated getter for column operation_code.
     * Column description: 
     *
     * @return the requested value
     */
    public String getOperationcode();

    /**
     * Generated setter for column operation_code.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setOperationcode(String value);

    /**
     * Generated getter for column operation_name.
     * Column description: 
     *
     * @return the requested value
     */
    public String getOperationname();

    /**
     * Generated setter for column operation_name.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setOperationname(String value);

    /**
     * Generated getter for column part_number.
     * Column description: 
     *
     * @return the requested value
     */
    public String getPartnumber();

    /**
     * Generated setter for column part_number.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setPartnumber(String value);

    /**
     * Generated getter for column scan_time.
     * Column description: 
     *
     * @return the requested value
     */
    public Time getScantime();

    /**
     * Generated setter for column scan_time.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setScantime(Time value);

    /**
     * Generated getter for column send_status.
     * Column description: 
     *
     * @return the requested value
     */
    public String getSendstatus();

    /**
     * Generated setter for column send_status.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setSendstatus(String value);

    /**
     * Generated getter for column send_time.
     * Column description: 
     *
     * @return the requested value
     */
    public Time getSendtime();

    /**
     * Generated setter for column send_time.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setSendtime(Time value);

    /**
     * Generated getter for column station.
     * Column description: 
     *
     * @return the requested value
     */
    public String getStation();

    /**
     * Generated setter for column station.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setStation(String value);

    /**
     * Generated getter for column step_code.
     * Column description: 
     *
     * @return the requested value
     */
    public String getStepcode();

    /**
     * Generated setter for column step_code.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setStepcode(String value);

    /**
     * Generated getter for column step_name.
     * Column description: 
     *
     * @return the requested value
     */
    public String getStepname();

    /**
     * Generated setter for column step_name.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setStepname(String value);

    /**
     * Generated getter for column user_name.
     * Column description: 
     *
     * @return the requested value
     */
    public String getUsername();

    /**
     * Generated setter for column user_name.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setUsername(String value);

    /**
     * Generated getter for column vin.
     * Column description: 
     *
     * @return the requested value
     */
    public String getVin();

    /**
     * Generated setter for column vin.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setVin(String value);

}
