package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.Server;

import ... tbd ... // TODO Please specify package name.IMESASIMExactlyBindingFilter;
import ... tbd ... // TODO Please specify package name.MESGeneratedASIMExactlyBindingFilter;

/**
 * Generated filter class for application table AS_IM_ExactlyBinding.
 */
public class MESASIMExactlyBindingFilter extends MESGeneratedASIMExactlyBindingFilter //nl
                                              implements IMESASIMExactlyBindingFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESASIMExactlyBindingFilter(Server server) {
        super(server);
    }

    /**
     * Generated default constructor
     */
    public MESASIMExactlyBindingFilter() {
        super();
    }
}
