// CHECKSTYLE:FileLength:off (reason:generated)
// CHECKSTYLE:LineLength:off (reason:generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESATObject;

import com.datasweep.compatibility.ui.Time;

/**
 * Generated interface definition for application table AS_IM_OrderCL.
 * Application table description: null
 * @ftps.exclude 
 */
public interface IMESGeneratedASIMOrderCL extends IMESATObject {

    /** Generated attribute definition */
    public static final String ATDEFINITION_NAME = "AS_IM_OrderCL";


    /** Generated property name */
    public static final String PROP_NAME_LINE = "line";

    /** Generated column name */
    public static final String SQL_COL_NAME_LINE = "line_S";
    

    /** Generated property name */
    public static final String PROP_NAME_MODEL = "model";

    /** Generated column name */
    public static final String SQL_COL_NAME_MODEL = "model_S";
    

    /** Generated property name */
    public static final String PROP_NAME_ORDERNUM = "ordernum";

    /** Generated column name */
    public static final String SQL_COL_NAME_ORDERNUM = "order_num_S";
    

    /** Generated property name */
    public static final String PROP_NAME_PASSTIME = "passtime";

    /** Generated column name */
    public static final String SQL_COL_NAME_PASSTIME = "pass_time_T";
    

    /** Generated property name */
    public static final String PROP_NAME_PLANT = "plant";

    /** Generated column name */
    public static final String SQL_COL_NAME_PLANT = "plant_S";
    

    /** Generated property name */
    public static final String PROP_NAME_SENDSTATUS = "sendstatus";

    /** Generated column name */
    public static final String SQL_COL_NAME_SENDSTATUS = "send_status_I";
    

    /** Generated property name */
    public static final String PROP_NAME_SENDTIME = "sendtime";

    /** Generated column name */
    public static final String SQL_COL_NAME_SENDTIME = "send_time_T";
    

    /** Generated property name */
    public static final String PROP_NAME_STATION = "station";

    /** Generated column name */
    public static final String SQL_COL_NAME_STATION = "station_S";
    

    /** Generated property name */
    public static final String PROP_NAME_TSN = "tsn";

    /** Generated column name */
    public static final String SQL_COL_NAME_TSN = "tsn_S";
    

    /** Generated property name */
    public static final String PROP_NAME_VIN = "vin";

    /** Generated column name */
    public static final String SQL_COL_NAME_VIN = "vin_S";
    

    /** Generated property name */
    public static final String PROP_NAME_WORKORDER = "workorder";

    /** Generated column name */
    public static final String SQL_COL_NAME_WORKORDER = "work_order_I";
    
    /**
     * Generated getter for column line.
     * Column description: 
     *
     * @return the requested value
     */
    public String getLine();

    /**
     * Generated setter for column line.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setLine(String value);

    /**
     * Generated getter for column model.
     * Column description: 车型
     *
     * @return the requested value
     */
    public String getModel();

    /**
     * Generated setter for column model.
     * Column description: 车型
     *
     * @param value The new value to be assigned
     */
    public void setModel(String value);

    /**
     * Generated getter for column order_num.
     * Column description: 
     *
     * @return the requested value
     */
    public String getOrdernum();

    /**
     * Generated setter for column order_num.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setOrdernum(String value);

    /**
     * Generated getter for column pass_time.
     * Column description: 
     *
     * @return the requested value
     */
    public Time getPasstime();

    /**
     * Generated setter for column pass_time.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setPasstime(Time value);

    /**
     * Generated getter for column plant.
     * Column description: 工厂代码
     *
     * @return the requested value
     */
    public String getPlant();

    /**
     * Generated setter for column plant.
     * Column description: 工厂代码
     *
     * @param value The new value to be assigned
     */
    public void setPlant(String value);

    /**
     * Generated getter for column send_status.
     * Column description: 
     *
     * @return the requested value
     */
    public Long getSendstatus();

    /**
     * Generated setter for column send_status.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setSendstatus(Long value);

    /**
     * Generated getter for column send_time.
     * Column description: 
     *
     * @return the requested value
     */
    public Time getSendtime();

    /**
     * Generated setter for column send_time.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setSendtime(Time value);

    /**
     * Generated getter for column station.
     * Column description: 
     *
     * @return the requested value
     */
    public String getStation();

    /**
     * Generated setter for column station.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setStation(String value);

    /**
     * Generated getter for column tsn.
     * Column description: 
     *
     * @return the requested value
     */
    public String getTsn();

    /**
     * Generated setter for column tsn.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setTsn(String value);

    /**
     * Generated getter for column vin.
     * Column description: 
     *
     * @return the requested value
     */
    public String getVin();

    /**
     * Generated setter for column vin.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setVin(String value);

    /**
     * Generated getter for column work_order.
     * Column description: 
     *
     * @return the requested value
     */
    public Long getWorkorder();

    /**
     * Generated setter for column work_order.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setWorkorder(Long value);

}
