package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.Server;

import ... tbd ... // TODO Please specify package name.IMESASIMOrderCLFilter;
import ... tbd ... // TODO Please specify package name.MESGeneratedASIMOrderCLFilter;

/**
 * Generated filter class for application table AS_IM_OrderCL.
 */
public class MESASIMOrderCLFilter extends MESGeneratedASIMOrderCLFilter //nl
                                              implements IMESASIMOrderCLFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESASIMOrderCLFilter(Server server) {
        super(server);
    }

    /**
     * Generated default constructor
     */
    public MESASIMOrderCLFilter() {
        super();
    }
}
