// CHECKSTYLE:FileLength:off (reason:generated)
// CHECKSTYLE:LineLength:off (reason:generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESATObject;

import com.datasweep.compatibility.client.Order;

/**
 * Generated interface definition for application table AS_OM_TrialCarLock.
 * Application table description: null
 * @ftps.exclude 
 */
public interface IMESGeneratedASOMTrialCarLock extends IMESATObject {

    /** Generated attribute definition */
    public static final String ATDEFINITION_NAME = "AS_OM_TrialCarLock";


    /** Generated property name */
    public static final String PROP_NAME_BSN = "bsn";

    /** Generated column name */
    public static final String SQL_COL_NAME_BSN = "bsn_S";
    

    /** Generated property name */
    public static final String PROP_NAME_MIX = "mix";

    /** Generated column name */
    public static final String SQL_COL_NAME_MIX = "mix_S";
    

    /** Generated property name */
    public static final String PROP_NAME_MODEL = "model";

    /** Generated column name */
    public static final String SQL_COL_NAME_MODEL = "model_S";
    

    /** Generated property name */
    public static final String PROP_NAME_ORDER = "order";

    /** Generated column name */
    public static final String SQL_COL_NAME_ORDER = "order_" + IObjectTypes.TYPE_ORDER;
    

    /** Generated property name */
    public static final String PROP_NAME_ORDERNUMBER = "ordernumber";

    /** Generated column name */
    public static final String SQL_COL_NAME_ORDERNUMBER = "order_number_S";
    

    /** Generated property name */
    public static final String PROP_NAME_STATUS = "status";

    /** Generated column name */
    public static final String SQL_COL_NAME_STATUS = "status_S";
    

    /** Generated property name */
    public static final String PROP_NAME_USER = "user";

    /** Generated column name */
    public static final String SQL_COL_NAME_USER = "user_S";
    

    /** Generated property name */
    public static final String PROP_NAME_VIN = "vin";

    /** Generated column name */
    public static final String SQL_COL_NAME_VIN = "vin_S";
    
    /**
     * Generated getter for column bsn.
     * Column description: BSN
     *
     * @return the requested value
     */
    public String getBsn();

    /**
     * Generated setter for column bsn.
     * Column description: BSN
     *
     * @param value The new value to be assigned
     */
    public void setBsn(String value);

    /**
     * Generated getter for column mix.
     * Column description: MIX
     *
     * @return the requested value
     */
    public String getMix();

    /**
     * Generated setter for column mix.
     * Column description: MIX
     *
     * @param value The new value to be assigned
     */
    public void setMix(String value);

    /**
     * Generated getter for column model.
     * Column description: 车型
     *
     * @return the requested value
     */
    public String getModel();

    /**
     * Generated setter for column model.
     * Column description: 车型
     *
     * @param value The new value to be assigned
     */
    public void setModel(String value);

    /**
     * Generated getter for column order.
     * Column description: 订单
     *
     * @return the requested value
     */
    public Order getOrder();

    /**
     * Generated setter for column order.
     * Column description: 订单
     *
     * @param value The new value to be assigned
     */
    public void setOrder(Order value);

    /**
     * Generated getter for column order_number.
     * Column description: 订单号
     *
     * @return the requested value
     */
    public String getOrdernumber();

    /**
     * Generated setter for column order_number.
     * Column description: 订单号
     *
     * @param value The new value to be assigned
     */
    public void setOrdernumber(String value);

    /**
     * Generated getter for column status.
     * Column description: 是否启用
     *
     * @return the requested value
     */
    public String getStatus();

    /**
     * Generated setter for column status.
     * Column description: 是否启用
     *
     * @param value The new value to be assigned
     */
    public void setStatus(String value);

    /**
     * Generated getter for column user.
     * Column description: 创建人
     *
     * @return the requested value
     */
    public String getUser();

    /**
     * Generated setter for column user.
     * Column description: 创建人
     *
     * @param value The new value to be assigned
     */
    public void setUser(String value);

    /**
     * Generated getter for column vin.
     * Column description: VIN
     *
     * @return the requested value
     */
    public String getVin();

    /**
     * Generated setter for column vin.
     * Column description: VIN
     *
     * @param value The new value to be assigned
     */
    public void setVin(String value);

}
