package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESObject;

import ... tbd ... // TODO Please specify package name.IMESGeneratedASOMTrialCarLock;

/**
 * Generated interface definition for application table AS_OM_TrialCarLock.
 * Application table description: null<br>
 * @ftps.exclude 
 */
public interface IMESASOMTrialCarLock extends IMESGeneratedASOMTrialCarLock, IMESObject {
}
