package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import ... tbd ... // TODO Please specify package name.IMESGeneratedASOMTrialCarLockFilter;

/**
 * Generated filter interface for application table AS_OM_TrialCarLock.
 * @ftps.exclude 
 */
public interface IMESASOMTrialCarLockFilter extends IMESGeneratedASOMTrialCarLockFilter {
}
