// CHECKSTYLE:FileLength:off (reason:generated)
// CHECKSTYLE:LineLength:off (reason:generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import java.util.List;

import com.datasweep.compatibility.client.DatasweepException;
import com.rockwell.mes.commons.base.ifc.objects.IMESATObjectFilter;

import ... tbd ... // TODO Please specify package name.IMESASOMTrialCarLock;
import ... tbd ... // TODO Please specify package name.IMESASOMTrialCarLockFilter;

import com.datasweep.compatibility.client.Order;

/**
 * Generated filter interface for application table AS_OM_TrialCarLock.
 * @ftps.exclude 
 */
public interface IMESGeneratedASOMTrialCarLockFilter extends IMESATObjectFilter  {

    /**
     * Generated method definition
     *
     * @return the list of the objects
     */
    public List<IMESASOMTrialCarLock> getFilteredObjects();

    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forBsnContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forBsnEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forBsnNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forBsnStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forMixContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forMixEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forMixNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forMixStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forModelContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forModelEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forModelNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forModelStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forOrderEqualTo(Order value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forOrderNotEqualTo(Order value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forOrdernumberContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forOrdernumberEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forOrdernumberNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forOrdernumberStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forStatusContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forStatusEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forStatusNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forStatusStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forUserContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forUserEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forUserNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forUserStartingWith(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forVinContaining(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forVinEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forVinNotEqualTo(String value) throws DatasweepException;
    /**
     * Generated method definition
     *
     * @param value the value to be filtered for
     * @return the filter object
     * @throws DatasweepException thrown when error occurs
     */
    public IMESASOMTrialCarLockFilter forVinStartingWith(String value) throws DatasweepException;
}
