package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.Server;

import ... tbd ... // TODO Please specify package name.IMESASOMTrialCarLockFilter;
import ... tbd ... // TODO Please specify package name.MESGeneratedASOMTrialCarLockFilter;

/**
 * Generated filter class for application table AS_OM_TrialCarLock.
 */
public class MESASOMTrialCarLockFilter extends MESGeneratedASOMTrialCarLockFilter //nl
                                              implements IMESASOMTrialCarLockFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESASOMTrialCarLockFilter(Server server) {
        super(server);
    }

    /**
     * Generated default constructor
     */
    public MESASOMTrialCarLockFilter() {
        super();
    }
}
