// CHECKSTYLE:FileLength:off (reason:generated)
// CHECKSTYLE:LineLength:off (reason:generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESATObject;


/**
 * Generated interface definition for application table AS_IM_AdasDetection.
 * Application table description: null
 * @ftps.exclude 
 */
public interface IMESGeneratedASIMAdasDetection extends IMESATObject {

    /** Generated attribute definition */
    public static final String ATDEFINITION_NAME = "AS_IM_AdasDetection";


    /** Generated property name */
    public static final String PROP_NAME_ACC = "acc";

    /** Generated column name */
    public static final String SQL_COL_NAME_ACC = "acc_S";
    

    /** Generated property name */
    public static final String PROP_NAME_ACCHORANGLE = "acchorangle";

    /** Generated column name */
    public static final String SQL_COL_NAME_ACCHORANGLE = "acchorangle_S";
    

    /** Generated property name */
    public static final String PROP_NAME_ACCVERANGLE = "accverangle";

    /** Generated column name */
    public static final String SQL_COL_NAME_ACCVERANGLE = "accverangle_S";
    

    /** Generated property name */
    public static final String PROP_NAME_BSD = "bsd";

    /** Generated column name */
    public static final String SQL_COL_NAME_BSD = "bsd_S";
    

    /** Generated property name */
    public static final String PROP_NAME_LKA = "lka";

    /** Generated column name */
    public static final String SQL_COL_NAME_LKA = "lka_S";
    

    /** Generated property name */
    public static final String PROP_NAME_ZLINENO = "zlineno";

    /** Generated column name */
    public static final String SQL_COL_NAME_ZLINENO = "zlineno_S";
    

    /** Generated property name */
    public static final String PROP_NAME_ZOVERALLRESULT = "zoverallresult";

    /** Generated column name */
    public static final String SQL_COL_NAME_ZOVERALLRESULT = "zoverallresult_S";
    

    /** Generated property name */
    public static final String PROP_NAME_ZPLANT = "zplant";

    /** Generated column name */
    public static final String SQL_COL_NAME_ZPLANT = "zplant_S";
    

    /** Generated property name */
    public static final String PROP_NAME_ZVIN = "zvin";

    /** Generated column name */
    public static final String SQL_COL_NAME_ZVIN = "zvin_S";
    
    /**
     * Generated getter for column acc.
     * Column description: ACC标定结果
     *
     * @return the requested value
     */
    public String getAcc();

    /**
     * Generated setter for column acc.
     * Column description: ACC标定结果
     *
     * @param value The new value to be assigned
     */
    public void setAcc(String value);

    /**
     * Generated getter for column acchorangle.
     * Column description: ACC标定水平角度
     *
     * @return the requested value
     */
    public String getAcchorangle();

    /**
     * Generated setter for column acchorangle.
     * Column description: ACC标定水平角度
     *
     * @param value The new value to be assigned
     */
    public void setAcchorangle(String value);

    /**
     * Generated getter for column accverangle.
     * Column description: ACC标定垂直角度
     *
     * @return the requested value
     */
    public String getAccverangle();

    /**
     * Generated setter for column accverangle.
     * Column description: ACC标定垂直角度
     *
     * @param value The new value to be assigned
     */
    public void setAccverangle(String value);

    /**
     * Generated getter for column bsd.
     * Column description: BSD标定结果
     *
     * @return the requested value
     */
    public String getBsd();

    /**
     * Generated setter for column bsd.
     * Column description: BSD标定结果
     *
     * @param value The new value to be assigned
     */
    public void setBsd(String value);

    /**
     * Generated getter for column lka.
     * Column description: LKA标定结果
     *
     * @return the requested value
     */
    public String getLka();

    /**
     * Generated setter for column lka.
     * Column description: LKA标定结果
     *
     * @param value The new value to be assigned
     */
    public void setLka(String value);

    /**
     * Generated getter for column zlineno.
     * Column description: 检测线号
     *
     * @return the requested value
     */
    public String getZlineno();

    /**
     * Generated setter for column zlineno.
     * Column description: 检测线号
     *
     * @param value The new value to be assigned
     */
    public void setZlineno(String value);

    /**
     * Generated getter for column zoverallresult.
     * Column description: 总评结果
     *
     * @return the requested value
     */
    public String getZoverallresult();

    /**
     * Generated setter for column zoverallresult.
     * Column description: 总评结果
     *
     * @param value The new value to be assigned
     */
    public void setZoverallresult(String value);

    /**
     * Generated getter for column zplant.
     * Column description: 工厂代码
     *
     * @return the requested value
     */
    public String getZplant();

    /**
     * Generated setter for column zplant.
     * Column description: 工厂代码
     *
     * @param value The new value to be assigned
     */
    public void setZplant(String value);

    /**
     * Generated getter for column zvin.
     * Column description: 车辆 VIN 号
     *
     * @return the requested value
     */
    public String getZvin();

    /**
     * Generated setter for column zvin.
     * Column description: 车辆 VIN 号
     *
     * @param value The new value to be assigned
     */
    public void setZvin(String value);

}
