package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.ATRow;

import ... tbd ... // TODO Please specify package name.IMESASIMAdasDetection;
import ... tbd ... // TODO Please specify package name.MESGeneratedASIMAdasDetection;

/**
 * Generated class definition for application table AS_IM_AdasDetection.
 * Application table description: null
 */
public class MESASIMAdasDetection extends MESGeneratedASIMAdasDetection //nl
                                        implements IMESASIMAdasDetection {

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESASIMAdasDetection(long key) {
        super(key);
    }

    /**
     * Generated constructor
     *
     * @param source the source to copy.
     */
    public MESASIMAdasDetection(MESASIMAdasDetection source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESASIMAdasDetection(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESASIMAdasDetection() {
        super();
    }

}
