package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.Server;

import ... tbd ... // TODO Please specify package name.IMESASIMDmsNoFilter;
import ... tbd ... // TODO Please specify package name.MESGeneratedASIMDmsNoFilter;

/**
 * Generated filter class for application table AS_IM_Dms_No.
 */
public class MESASIMDmsNoFilter extends MESGeneratedASIMDmsNoFilter //nl
                                              implements IMESASIMDmsNoFilter {

    /** Generated attribute definition */
    private static final long serialVersionUID = 1L;

    /**
     * Generated constructor
     *
     * @param server The Server object
     */
    public MESASIMDmsNoFilter(Server server) {
        super(server);
    }

    /**
     * Generated default constructor
     */
    public MESASIMDmsNoFilter() {
        super();
    }
}
