// CHECKSTYLE:FileLength:off (reason: generated)
// CHECKSTYLE:LineLength:off (reason: generated)
// CHECKSTYLE:MethodLength:off (reason: generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file is generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
 
import java.util.List;
 
import com.datasweep.compatibility.client.ATRow; 
import com.datasweep.compatibility.client.AccessPrivilege;
import com.datasweep.compatibility.client.DatasweepException;
import com.datasweep.compatibility.client.Response;
import com.datasweep.compatibility.client.Server;
import com.datasweep.compatibility.ui.Time;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;

import ... tbd ... // TODO Please specify package name.IMESASIMDmsNo;
import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMDmsNo;
import ... tbd ... // TODO Please specify package name.MESASIMDmsNo;
import ... tbd ... // TODO Please specify package name.MESASIMDmsNoFilter;


/**
 * Generated class definition for application table AS_IM_Dms_No.
 * Application table description: null
 */
public class MESGeneratedASIMDmsNo extends MESATObject //nl
                                                 implements IMESGeneratedASIMDmsNo {


    /** Generated column name */
    public static final String COL_NAME_ACQUIRETIME = "acquire_time";

    /** Generated column name */
    public static final String COL_NAME_FILENAME = "file_name";

    /** Generated column name */
    public static final String COL_NAME_FILEPATH = "file_path";

    /** Generated column name */
    public static final String COL_NAME_REASON = "reason";

    /** Generated column name */
    public static final String COL_NAME_RESULT = "result";

    /** Generated column name */
    public static final String COL_NAME_STATUS = "status";

    /** Generated column name */
    public static final String COL_NAME_SVONO = "svo_no";

    @Override
    public String getATDefinitionName() {
        return ATDEFINITION_NAME;
    }
    
    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESGeneratedASIMDmsNo(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     *
     * @param source The source to copy.
     */
    public MESGeneratedASIMDmsNo(MESGeneratedASIMDmsNo source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESGeneratedASIMDmsNo(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESGeneratedASIMDmsNo() {
        super();
    }

    /**
     * Generated method definition
     *
     * @param server The Server object
     * @return the filter object
     */
    public static MESASIMDmsNoFilter createFilter(Server server) {
        return new MESASIMDmsNoFilter(server);
    }

    /**
     * Generated method definition
     *
     * @return the filter object
     */
    public static MESASIMDmsNoFilter createFilter() {
        return new MESASIMDmsNoFilter();
    }

    /**
     * Generated method definition
     *
     * @param filter the Filter object
     * @return the list of the objects
     */
    public static List<IMESASIMDmsNo> getFilteredObjects(MESASIMDmsNoFilter filter) {
        return MESATObject.getFilteredMESATObjectList(filter, MESASIMDmsNo.class);
    }

    @Override
    public boolean refresh() {
        boolean ok = super.refresh();
        if (!ok) {
            return false;
        }
        
        return true;
    }    

    @Override
    public Time getAcquiretime() {
        return (Time) this.dgtATRow.getValue(COL_NAME_ACQUIRETIME);
    }

    @Override
    public void setAcquiretime(Time value) {
        Time oldValue = this.getAcquiretime();
        this.dgtATRow.setValue(COL_NAME_ACQUIRETIME, value);
        pcs.firePropertyChange(PROP_NAME_ACQUIRETIME, oldValue, value);
    }

    @Override
    public String getFilename() {
        return (String) this.dgtATRow.getValue(COL_NAME_FILENAME);
    }

    @Override
    public void setFilename(String value) {
        String oldValue = this.getFilename();
        this.dgtATRow.setValue(COL_NAME_FILENAME, value);
        pcs.firePropertyChange(PROP_NAME_FILENAME, oldValue, value);
    }

    @Override
    public String getFilepath() {
        return (String) this.dgtATRow.getValue(COL_NAME_FILEPATH);
    }

    @Override
    public void setFilepath(String value) {
        String oldValue = this.getFilepath();
        this.dgtATRow.setValue(COL_NAME_FILEPATH, value);
        pcs.firePropertyChange(PROP_NAME_FILEPATH, oldValue, value);
    }

    @Override
    public String getReason() {
        return (String) this.dgtATRow.getValue(COL_NAME_REASON);
    }

    @Override
    public void setReason(String value) {
        String oldValue = this.getReason();
        this.dgtATRow.setValue(COL_NAME_REASON, value);
        pcs.firePropertyChange(PROP_NAME_REASON, oldValue, value);
    }

    @Override
    public String getResult() {
        return (String) this.dgtATRow.getValue(COL_NAME_RESULT);
    }

    @Override
    public void setResult(String value) {
        String oldValue = this.getResult();
        this.dgtATRow.setValue(COL_NAME_RESULT, value);
        pcs.firePropertyChange(PROP_NAME_RESULT, oldValue, value);
    }

    @Override
    public Long getStatus() {
        return (Long) this.dgtATRow.getValue(COL_NAME_STATUS);
    }

    @Override
    public void setStatus(Long value) {
        Long oldValue = this.getStatus();
        this.dgtATRow.setValue(COL_NAME_STATUS, value);
        pcs.firePropertyChange(PROP_NAME_STATUS, oldValue, value);
    }

    @Override
    public String getSvono() {
        return (String) this.dgtATRow.getValue(COL_NAME_SVONO);
    }

    @Override
    public void setSvono(String value) {
        String oldValue = this.getSvono();
        this.dgtATRow.setValue(COL_NAME_SVONO, value);
        pcs.firePropertyChange(PROP_NAME_SVONO, oldValue, value);
    }

    // CHECKSTYLE:MethodNameCheck:off
    @Override
    public void Save(Time time, String comment, AccessPrivilege accessPrivilege) throws DatasweepException {
        // Check if attached reference is valid:
        Response res = new Response();
        if (res.isError()) {
            throw new DatasweepException(res);
        }
        // okay, save here.
        super.Save(time, comment, accessPrivilege);
    }
     // CHECKSTYLE:MethodNameCheck:on
     
}
