// CHECKSTYLE:FileLength:off (reason:generated)
// CHECKSTYLE:LineLength:off (reason:generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESATObject;

import com.datasweep.compatibility.ui.Time;

/**
 * Generated interface definition for application table AS_IM_VCATS_Broadcast.
 * Application table description: null
 * @ftps.exclude 
 */
public interface IMESGeneratedASIMVCATSBroadcast extends IMESATObject {

    /** Generated attribute definition */
    public static final String ATDEFINITION_NAME = "AS_IM_VCATS_Broadcast";


    /** Generated property name */
    public static final String PROP_NAME_ECU = "ecu";

    /** Generated column name */
    public static final String SQL_COL_NAME_ECU = "ecu_S";
    

    /** Generated property name */
    public static final String PROP_NAME_EOC = "eoc";

    /** Generated column name */
    public static final String SQL_COL_NAME_EOC = "eoc_S";
    

    /** Generated property name */
    public static final String PROP_NAME_MODEYEAR = "modeyear";

    /** Generated column name */
    public static final String SQL_COL_NAME_MODEYEAR = "mode_year_S";
    

    /** Generated property name */
    public static final String PROP_NAME_SAP = "sap";

    /** Generated column name */
    public static final String SQL_COL_NAME_SAP = "sap_S";
    

    /** Generated property name */
    public static final String PROP_NAME_SENDSTATUS = "sendstatus";

    /** Generated column name */
    public static final String SQL_COL_NAME_SENDSTATUS = "send_status_I";
    

    /** Generated property name */
    public static final String PROP_NAME_SENDTIME = "sendtime";

    /** Generated column name */
    public static final String SQL_COL_NAME_SENDTIME = "send_time_T";
    

    /** Generated property name */
    public static final String PROP_NAME_VIN = "vin";

    /** Generated column name */
    public static final String SQL_COL_NAME_VIN = "vin_S";
    
    /**
     * Generated getter for column ecu.
     * Column description: 
     *
     * @return the requested value
     */
    public String getEcu();

    /**
     * Generated setter for column ecu.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setEcu(String value);

    /**
     * Generated getter for column eoc.
     * Column description: 
     *
     * @return the requested value
     */
    public String getEoc();

    /**
     * Generated setter for column eoc.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setEoc(String value);

    /**
     * Generated getter for column mode_year.
     * Column description: 
     *
     * @return the requested value
     */
    public String getModeyear();

    /**
     * Generated setter for column mode_year.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setModeyear(String value);

    /**
     * Generated getter for column sap.
     * Column description: 整车物料号
     *
     * @return the requested value
     */
    public String getSap();

    /**
     * Generated setter for column sap.
     * Column description: 整车物料号
     *
     * @param value The new value to be assigned
     */
    public void setSap(String value);

    /**
     * Generated getter for column send_status.
     * Column description: 
     *
     * @return the requested value
     */
    public Long getSendstatus();

    /**
     * Generated setter for column send_status.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setSendstatus(Long value);

    /**
     * Generated getter for column send_time.
     * Column description: 
     *
     * @return the requested value
     */
    public Time getSendtime();

    /**
     * Generated setter for column send_time.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setSendtime(Time value);

    /**
     * Generated getter for column vin.
     * Column description: 
     *
     * @return the requested value
     */
    public String getVin();

    /**
     * Generated setter for column vin.
     * Column description: 
     *
     * @param value The new value to be assigned
     */
    public void setVin(String value);

}
