package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.rockwell.mes.commons.base.ifc.objects.IMESObject;

import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMVCATSBroadcast;

/**
 * Generated interface definition for application table AS_IM_VCATS_Broadcast.
 * Application table description: null<br>
 * @ftps.exclude 
 */
public interface IMESASIMVCATSBroadcast extends IMESGeneratedASIMVCATSBroadcast, IMESObject {
}
