package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMVCATSBroadcastFilter;

/**
 * Generated filter interface for application table AS_IM_VCATS_Broadcast.
 * @ftps.exclude 
 */
public interface IMESASIMVCATSBroadcastFilter extends IMESGeneratedASIMVCATSBroadcastFilter {
}
