package ... tbd ... // TODO Please specify package name;

/**
 * This file was generated by ATDefAccessClassGenerator and FMPP 2.3.15
 */
import com.datasweep.compatibility.client.ATRow;

import ... tbd ... // TODO Please specify package name.IMESASIMVCATSBroadcast;
import ... tbd ... // TODO Please specify package name.MESGeneratedASIMVCATSBroadcast;

/**
 * Generated class definition for application table AS_IM_VCATS_Broadcast.
 * Application table description: null
 */
public class MESASIMVCATSBroadcast extends MESGeneratedASIMVCATSBroadcast //nl
                                        implements IMESASIMVCATSBroadcast {

    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESASIMVCATSBroadcast(long key) {
        super(key);
    }

    /**
     * Generated constructor
     *
     * @param source the source to copy.
     */
    public MESASIMVCATSBroadcast(MESASIMVCATSBroadcast source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESASIMVCATSBroadcast(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESASIMVCATSBroadcast() {
        super();
    }

}
