// CHECKSTYLE:FileLength:off (reason: generated)
// CHECKSTYLE:LineLength:off (reason: generated)
// CHECKSTYLE:MethodLength:off (reason: generated)
package ... tbd ... // TODO Please specify package name;

/**
 * This file is generated by ATDefAccessClassGenerator and FMPP 2.3.15
 *
 * Please do not modify this file manually !!
 */
 
import java.util.List;
 
import com.datasweep.compatibility.client.ATRow; 
import com.datasweep.compatibility.client.AccessPrivilege;
import com.datasweep.compatibility.client.DatasweepException;
import com.datasweep.compatibility.client.Response;
import com.datasweep.compatibility.client.Server;
import com.datasweep.compatibility.ui.Time;
import com.rockwell.mes.commons.base.ifc.objects.MESATObject;

import ... tbd ... // TODO Please specify package name.IMESASIMVCATSBroadcast;
import ... tbd ... // TODO Please specify package name.IMESGeneratedASIMVCATSBroadcast;
import ... tbd ... // TODO Please specify package name.MESASIMVCATSBroadcast;
import ... tbd ... // TODO Please specify package name.MESASIMVCATSBroadcastFilter;


/**
 * Generated class definition for application table AS_IM_VCATS_Broadcast.
 * Application table description: null
 */
public class MESGeneratedASIMVCATSBroadcast extends MESATObject //nl
                                                 implements IMESGeneratedASIMVCATSBroadcast {


    /** Generated column name */
    public static final String COL_NAME_ECU = "ecu";

    /** Generated column name */
    public static final String COL_NAME_EOC = "eoc";

    /** Generated column name */
    public static final String COL_NAME_MODEYEAR = "mode_year";

    /** Generated column name */
    public static final String COL_NAME_SAP = "sap";

    /** Generated column name */
    public static final String COL_NAME_SENDSTATUS = "send_status";

    /** Generated column name */
    public static final String COL_NAME_SENDTIME = "send_time";

    /** Generated column name */
    public static final String COL_NAME_VIN = "vin";

    @Override
    public String getATDefinitionName() {
        return ATDEFINITION_NAME;
    }
    
    /**
     * Generated constructor
     *
     * @param key The key of the ATRow to load.
     */
    public MESGeneratedASIMVCATSBroadcast(long key) {
        super(key);
    }

    /**
     * Generated copy constructor
     *
     * @param source The source to copy.
     */
    public MESGeneratedASIMVCATSBroadcast(MESGeneratedASIMVCATSBroadcast source) {
        super(source);
    }

    /**
     * Generated constructor
     *
     * @param baseATRow The ATRow to wrap.
     */
    public MESGeneratedASIMVCATSBroadcast(ATRow baseATRow) {
        super(baseATRow);
    }

    /**
     * Generated default constructor
     */
    public MESGeneratedASIMVCATSBroadcast() {
        super();
    }

    /**
     * Generated method definition
     *
     * @param server The Server object
     * @return the filter object
     */
    public static MESASIMVCATSBroadcastFilter createFilter(Server server) {
        return new MESASIMVCATSBroadcastFilter(server);
    }

    /**
     * Generated method definition
     *
     * @return the filter object
     */
    public static MESASIMVCATSBroadcastFilter createFilter() {
        return new MESASIMVCATSBroadcastFilter();
    }

    /**
     * Generated method definition
     *
     * @param filter the Filter object
     * @return the list of the objects
     */
    public static List<IMESASIMVCATSBroadcast> getFilteredObjects(MESASIMVCATSBroadcastFilter filter) {
        return MESATObject.getFilteredMESATObjectList(filter, MESASIMVCATSBroadcast.class);
    }

    @Override
    public boolean refresh() {
        boolean ok = super.refresh();
        if (!ok) {
            return false;
        }
        
        return true;
    }    

    @Override
    public String getEcu() {
        return (String) this.dgtATRow.getValue(COL_NAME_ECU);
    }

    @Override
    public void setEcu(String value) {
        String oldValue = this.getEcu();
        this.dgtATRow.setValue(COL_NAME_ECU, value);
        pcs.firePropertyChange(PROP_NAME_ECU, oldValue, value);
    }

    @Override
    public String getEoc() {
        return (String) this.dgtATRow.getValue(COL_NAME_EOC);
    }

    @Override
    public void setEoc(String value) {
        String oldValue = this.getEoc();
        this.dgtATRow.setValue(COL_NAME_EOC, value);
        pcs.firePropertyChange(PROP_NAME_EOC, oldValue, value);
    }

    @Override
    public String getModeyear() {
        return (String) this.dgtATRow.getValue(COL_NAME_MODEYEAR);
    }

    @Override
    public void setModeyear(String value) {
        String oldValue = this.getModeyear();
        this.dgtATRow.setValue(COL_NAME_MODEYEAR, value);
        pcs.firePropertyChange(PROP_NAME_MODEYEAR, oldValue, value);
    }

    @Override
    public String getSap() {
        return (String) this.dgtATRow.getValue(COL_NAME_SAP);
    }

    @Override
    public void setSap(String value) {
        String oldValue = this.getSap();
        this.dgtATRow.setValue(COL_NAME_SAP, value);
        pcs.firePropertyChange(PROP_NAME_SAP, oldValue, value);
    }

    @Override
    public Long getSendstatus() {
        return (Long) this.dgtATRow.getValue(COL_NAME_SENDSTATUS);
    }

    @Override
    public void setSendstatus(Long value) {
        Long oldValue = this.getSendstatus();
        this.dgtATRow.setValue(COL_NAME_SENDSTATUS, value);
        pcs.firePropertyChange(PROP_NAME_SENDSTATUS, oldValue, value);
    }

    @Override
    public Time getSendtime() {
        return (Time) this.dgtATRow.getValue(COL_NAME_SENDTIME);
    }

    @Override
    public void setSendtime(Time value) {
        Time oldValue = this.getSendtime();
        this.dgtATRow.setValue(COL_NAME_SENDTIME, value);
        pcs.firePropertyChange(PROP_NAME_SENDTIME, oldValue, value);
    }

    @Override
    public String getVin() {
        return (String) this.dgtATRow.getValue(COL_NAME_VIN);
    }

    @Override
    public void setVin(String value) {
        String oldValue = this.getVin();
        this.dgtATRow.setValue(COL_NAME_VIN, value);
        pcs.firePropertyChange(PROP_NAME_VIN, oldValue, value);
    }

    // CHECKSTYLE:MethodNameCheck:off
    @Override
    public void Save(Time time, String comment, AccessPrivilege accessPrivilege) throws DatasweepException {
        // Check if attached reference is valid:
        Response res = new Response();
        if (res.isError()) {
            throw new DatasweepException(res);
        }
        // okay, save here.
        super.Save(time, comment, accessPrivilege);
    }
     // CHECKSTYLE:MethodNameCheck:on
     
}
